#include "mylib.h"
#include "cex.h"

f64
mylib_add(f64 a, f64 b)
{
    return a + b;
}

CEX_NAMESPACE_DEF struct __cex_namespace__mylib mylib = {
    // Autogenerated by CEX
    // clang-format off

    .add = mylib_add,

    // clang-format on
};
