// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#include "serdegen.h"

//
// Autogenerated serde for Stock type
//
Exception serdegen__Stock__serialize(json_wr_c* jw, Stock* item) {
    if (!item) {
        json$wr_scope(jw, JsonType__null){
            json$wr_val(NULL);
        }
        return EOK;
    }
    json$wr_scope(jw, JsonType__obj){
        json$wr_key("id");
        json$wr_val(item->id);

        json$wr_key("ticker");
        if (unlikely(!item->ticker)) {
            jw->error = JsonError.null_field;
        }
        json$wr_val(item->ticker);

        json$wr_key("exchange");
        if (unlikely(!item->exchange)) {
            jw->error = JsonError.null_field;
        }
        json$wr_val(item->exchange);

    }
    return jw->error;
}
Exc serdegen__Stock__print(Stock* item, json_wr_kw* json_writer_kwargs) {
    json_wr_c jw;
    json_wr_kw kwargs = {.stream = stdout, .indent = 0, .simplified = true};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(json.wr.create(&jw, &kwargs));
    if (kwargs.simplified) {
        json.wr.print_val(&jw, "Stock(");
        Exc err = serdegen.Stock.serialize(&jw, item);
        json.wr.print_val(&jw, "%s%s%s)\n", (err) ? " [error: ": "", (err) ? err : "", (err) ? "]": "" );
        return err;
    } else {
        return serdegen.Stock.serialize(&jw, item);
    }
}
Exception serdegen__Stock__deserialize(json_rd_c* jr, Stock* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    u64 fields_mask = 0;
    json$rd_foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = JsonError.parsing;
            goto fail;
        } else if (str$eq(k, "id")) {
            fields_mask |= (1 << 0);
            if (!json$rd_is_type_compatible(jr, &out_item->id)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->id), fail);
        } else if (str$eq(k, "ticker")) {
            fields_mask |= (1 << 1);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                json$rd_egoto(jr, JsonError.null_field, fail);
            } else {
                str_s out_s = {0};
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_s, allc), fail);
                out_item->ticker = out_s.buf;
            }
        } else if (str$eq(k, "exchange")) {
            fields_mask |= (1 << 2);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                json$rd_egoto(jr, JsonError.null_field, fail);
            } else {
                str_s out_s = {0};
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_s, allc), fail);
                out_item->exchange = out_s.buf;
            }
        } else {
            jr->error = JsonError.unknown_field;
            goto fail;
        }
    }
    if (fields_mask != ((1 << 3) - 1)) {
        if (!jr->error) {
            jr->error = JsonError.missing_field;
        }
        goto fail;
    }
    if (!jr->error) {
        return EOK;
    }
fail: 
    serdegen.Stock.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Stock__destroy(Stock* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        mem$free(allc, item->ticker);
        mem$free(allc, item->exchange);
        memset(item, 0, sizeof(*item));
    }
}

//
// Autogenerated serde for Position type
//
Exception serdegen__Position__serialize(json_wr_c* jw, Position* item) {
    if (!item) {
        json$wr_scope(jw, JsonType__null){
            json$wr_val(NULL);
        }
        return EOK;
    }
    json$wr_scope(jw, JsonType__obj){
        json$wr_key("qty");
        json$wr_val(item->qty);

        json$wr_key("fill_price");
        json$wr_val(item->fill_price);

        json$wr_key("stock");
        if (unlikely(!item->stock)) {
            jw->error = JsonError.null_field;
        }
        e$except_silent (err, serdegen.Stock.serialize(jw, item->stock)) {
            jw->error = err;
        }

    }
    return jw->error;
}
Exc serdegen__Position__print(Position* item, json_wr_kw* json_writer_kwargs) {
    json_wr_c jw;
    json_wr_kw kwargs = {.stream = stdout, .indent = 0, .simplified = true};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(json.wr.create(&jw, &kwargs));
    if (kwargs.simplified) {
        json.wr.print_val(&jw, "Position(");
        Exc err = serdegen.Position.serialize(&jw, item);
        json.wr.print_val(&jw, "%s%s%s)\n", (err) ? " [error: ": "", (err) ? err : "", (err) ? "]": "" );
        return err;
    } else {
        return serdegen.Position.serialize(&jw, item);
    }
}
Exception serdegen__Position__deserialize(json_rd_c* jr, Position* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    u64 fields_mask = 0;
    json$rd_foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = JsonError.parsing;
            goto fail;
        } else if (str$eq(k, "qty")) {
            fields_mask |= (1 << 0);
            if (!json$rd_is_type_compatible(jr, &out_item->qty)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->qty), fail);
        } else if (str$eq(k, "fill_price")) {
            fields_mask |= (1 << 1);
            if (!json$rd_is_type_compatible(jr, &out_item->fill_price)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->fill_price), fail);
        } else if (str$eq(k, "stock")) {
            fields_mask |= (1 << 2);
            if (jr->type != JsonType__null) {
                if (jr->type != JsonType__obj) {
                    json$rd_egoto(jr, JsonError.wrong_type, fail);
                }
                out_item->stock = mem$new(allc, Stock);
                if (!out_item->stock) {
                    return Error.memory;
                }
                json$rd_egoto(jr, serdegen.Stock.deserialize(jr, out_item->stock, allc), fail);
            } else {
                json$rd_egoto(jr, JsonError.null_field, fail);
            }
        } else {
            jr->error = JsonError.unknown_field;
            goto fail;
        }
    }
    if (fields_mask != ((1 << 3) - 1)) {
        if (!jr->error) {
            jr->error = JsonError.missing_field;
        }
        goto fail;
    }
    if (!jr->error) {
        return EOK;
    }
fail: 
    serdegen.Position.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Position__destroy(Position* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        serdegen.Stock.destroy(item->stock, allc);
        mem$free(allc, item->stock);
        memset(item, 0, sizeof(*item));
    }
}

const struct __cex_namespace__serdegen serdegen = {
    // Autogenerated by CEX
    // clang-format off


    .Position = {
        .deserialize = serdegen__Position__deserialize,
        .destroy = serdegen__Position__destroy,
        .print = serdegen__Position__print,
        .serialize = serdegen__Position__serialize,
    },

    .Stock = {
        .deserialize = serdegen__Stock__deserialize,
        .destroy = serdegen__Stock__destroy,
        .print = serdegen__Stock__print,
        .serialize = serdegen__Stock__serialize,
    },

    // clang-format on
};
