// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#include "cex.h"
#include "cexstd/json/json.h"
#include "tests/cexstd/json//basic/Stock.h"
#include "tests/cexstd/json//basic/Position.h"

/// Generic `serdegen` type printer using json
/// Example: 
/// serdegen$print(any_supported_type_pointer, .indent = 0, .simplified = true ); 
#define serdegen$print(item, kwargs...) \
    _Generic((item), \
        Stock*: serdegen.Stock.print, \
        Position*: serdegen.Position.print\
    )(item, &(json_wr_kw) { kwargs })

struct __cex_namespace__serdegen {
    // Autogenerated by CEX
    // clang-format off


    struct {
        Exception       (*deserialize)(json_rd_c* jr, Position* out_item, IAllocator allc);
        void            (*destroy)(Position* item, IAllocator allc);
        Exc             (*print)(Position* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Position* item);
    } Position;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, Stock* out_item, IAllocator allc);
        void            (*destroy)(Stock* item, IAllocator allc);
        Exc             (*print)(Stock* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Stock* item);
    } Stock;

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__serdegen serdegen;

