// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#include "cex.h"
#include "cexstd/json/json.h"
#include "tests/cexstd/json//basic/Stock.h"
#include "tests/cexstd/json//basic/Position.h"

/// Generic `serdegen` type printer using json
/// Example: 
/// serdegen$print(any_supported_type_pointer, .indent = 0, .simplified = true ); 
#define serdegen$print(item, kwargs...) \
    _Generic((item), \
        Stock*: serdegen.Stock.print, \
        Position_c*: serdegen.Position.print, \
        foo_c*: serdegen.foo.print\
    )(item, &(json_wr_kw) { kwargs })

struct __cex_namespace__serdegen {
    // Autogenerated by CEX
    // clang-format off


    struct {
        Exception       (*deserialize)(json_rd_c* jr, Position_c* out_item, IAllocator allc);
        void            (*destroy)(Position_c* item, IAllocator allc);
        Exc             (*print)(Position_c* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Position_c* item);
    } Position;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, Stock* out_item, IAllocator allc);
        void            (*destroy)(Stock* item, IAllocator allc);
        Exc             (*print)(Stock* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Stock* item);
    } Stock;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, foo_c* out_item, IAllocator allc);
        void            (*destroy)(foo_c* item, IAllocator allc);
        Exc             (*print)(foo_c* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, foo_c* item);
    } foo;

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__serdegen serdegen;

