// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#include "serdegen.h"

//
// Autogenerated serde for Stock type
//
Exception serdegen__Stock__serialize(jw_c* jw, Stock* item) {
    if (!item) {
        jw$scope(jw, JsonType__null){
            jw$val(NULL);
        }
        return EOK;
    }
    jw$scope(jw, JsonType__obj){
        jw$key("id");
        jw$val(item->id);

        jw$key("ticker");
        jw$val(item->ticker);

        jw$key("exchange");
        jw$val(item->exchange);

    }
    return jw->error;
}
Exc serdegen__Stock__print(Stock* item, jw_kw* json_writer_kwargs) {
    jw_c jw;
    jw_kw kwargs = {.stream = stdout, .indent = 0};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(_cex_json__writer__create(&jw, &kwargs));
    return serdegen.Stock.serialize(&jw, item);
}
Exception serdegen__Stock__deserialize(jr_c* jr, Stock* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    jr$foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = Error.integrity;
            goto fail;
        } else if (str$eq(k, "id")) {
            e$except_silent(err, str$convert(v, &out_item->id)) {
                jr->error = err;
                goto fail;
            }

        } else if (str$eq(k, "ticker")) {
            out_item->ticker = str.slice.clone(v, allc);

        } else if (str$eq(k, "exchange")) {
            out_item->exchange = str.slice.clone(v, allc);

        }
    }
    return EOK;
fail: 
    serdegen.Stock.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Stock__destroy(Stock* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        mem$free(allc, item->ticker);
        mem$free(allc, item->exchange);
        memset(item, 0, sizeof(*item));
    }
}

//
// Autogenerated serde for Position type
//
Exception serdegen__Position__serialize(jw_c* jw, Position* item) {
    if (!item) {
        jw$scope(jw, JsonType__null){
            jw$val(NULL);
        }
        return EOK;
    }
    jw$scope(jw, JsonType__obj){
        jw$key("qty");
        jw$val(item->qty);

        jw$key("fill_price");
        jw$val(item->fill_price);

        jw$key("stock");
        e$except_silent (err, serdegen.Stock.serialize(jw, item->stock)) {
            jw->error = err;
        }

    }
    return jw->error;
}
Exc serdegen__Position__print(Position* item, jw_kw* json_writer_kwargs) {
    jw_c jw;
    jw_kw kwargs = {.stream = stdout, .indent = 0};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(_cex_json__writer__create(&jw, &kwargs));
    return serdegen.Position.serialize(&jw, item);
}
Exception serdegen__Position__deserialize(jr_c* jr, Position* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    jr$foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = Error.integrity;
            goto fail;
        } else if (str$eq(k, "qty")) {
            e$except_silent(err, str$convert(v, &out_item->qty)) {
                jr->error = err;
                goto fail;
            }

        } else if (str$eq(k, "fill_price")) {
            e$except_silent(err, str$convert(v, &out_item->fill_price)) {
                jr->error = err;
                goto fail;
            }

        } else if (str$eq(k, "stock")) {
            out_item->stock = mem$new(allc, Stock);
            e$except_silent (err, serdegen.Stock.deserialize(jr, out_item->stock, allc)) {
                jr->error = err;
                goto fail;
            }

        }
    }
    return EOK;
fail: 
    serdegen.Position.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Position__destroy(Position* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        serdegen.Stock.destroy(item->stock, allc);
        mem$free(allc, item->stock);
        memset(item, 0, sizeof(*item));
    }
}

const struct __cex_namespace__serdegen serdegen = {
    // Autogenerated by CEX
    // clang-format off


    .Position = {
        .deserialize = serdegen__Position__deserialize,
        .destroy = serdegen__Position__destroy,
        .print = serdegen__Position__print,
        .serialize = serdegen__Position__serialize,
    },

    .Stock = {
        .deserialize = serdegen__Stock__deserialize,
        .destroy = serdegen__Stock__destroy,
        .print = serdegen__Stock__print,
        .serialize = serdegen__Stock__serialize,
    },

    // clang-format on
};
