// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#include "serdegen.h"

//
// Autogenerated serde for Stock type
//
Exception serdegen__Stock__serialize(jw_c* jw, Stock* item) {
    if (!item) {
        jw$scope(jw, JsonType__null){
            jw$val(NULL);
        }
        return EOK;
    }
    jw$scope(jw, JsonType__obj){
        jw$key("id");
        jw$val(item->id);

        jw$key("ticker");
        jw$val(item->ticker);

        jw$key("exchange");
        jw$val(item->exchange);

    }
    return jw->error;
}
Exc serdegen__Stock__print(Stock* item, jw_kw* json_writer_kwargs) {
    jw_c jw;
    jw_kw kwargs = {.stream = stdout, .indent = 0};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(_cex_json__writer__create(&jw, &kwargs));
    return serdegen.Stock.serialize(&jw, item);
}
Exception serdegen__Stock__deserialize(jr_c* jr, Stock* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    jr$foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = Error.integrity;
            goto fail;
        } else if (str$eq(k, "id")) {
            e$except_silent(err, str$convert(v, &out_item->id)) {
                jr->error = err;
                goto fail;
            }

        } else if (str$eq(k, "ticker")) {
            if (!v.buf) {
                out_item->ticker = NULL;
            } else {
                out_item->ticker = str.slice.clone(v, allc);
            }

        } else if (str$eq(k, "exchange")) {
            if (!v.buf) {
                out_item->exchange = NULL;
            } else {
                out_item->exchange = str.slice.clone(v, allc);
            }

        }
    }
    return EOK;
fail: 
    serdegen.Stock.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Stock__destroy(Stock* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        mem$free(allc, item->ticker);
        mem$free(allc, item->exchange);
        memset(item, 0, sizeof(*item));
    }
}

//
// Autogenerated serde for ItemNullable type
//
Exception serdegen__ItemNullable__serialize(jw_c* jw, ItemNullable* item) {
    if (!item) {
        jw$scope(jw, JsonType__null){
            jw$val(NULL);
        }
        return EOK;
    }
    jw$scope(jw, JsonType__obj){
        jw$key("sbuf_field");
        jw$val(item->sbuf_field);

        jw$key("str_s_field");
        jw$val(item->str_s_field);

        jw$key("char_field");
        jw$val(item->char_field);

        jw$key("stock_field");
        e$except_silent (err, serdegen.Stock.serialize(jw, item->stock_field)) {
            jw->error = err;
        }

    }
    return jw->error;
}
Exc serdegen__ItemNullable__print(ItemNullable* item, jw_kw* json_writer_kwargs) {
    jw_c jw;
    jw_kw kwargs = {.stream = stdout, .indent = 0};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(_cex_json__writer__create(&jw, &kwargs));
    return serdegen.ItemNullable.serialize(&jw, item);
}
Exception serdegen__ItemNullable__deserialize(jr_c* jr, ItemNullable* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    jr$foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = Error.integrity;
            goto fail;
        } else if (str$eq(k, "sbuf_field")) {
            if (!v.buf) {
                out_item->sbuf_field = NULL;
            } else {
                out_item->sbuf_field = sbuf.create(v.len + sizeof(sbuf_head_s) + 1, allc);
                if (!out_item->sbuf_field) {
                    return Error.memory;
                }
                if (sbuf.appendf(&out_item->sbuf_field, "%S", v)) {
                    return Error.memory;
                }
            }

        } else if (str$eq(k, "str_s_field")) {
            if (!v.buf) {
                out_item->str_s_field = (str_s){0};
            } else {
                out_item->str_s_field = str.sstr(str.slice.clone(v, allc));
            }

        } else if (str$eq(k, "char_field")) {
            if (!v.buf) {
                out_item->char_field = NULL;
            } else {
                out_item->char_field = str.slice.clone(v, allc);
            }

        } else if (str$eq(k, "stock_field")) {
            if (jr->type != JsonType__null) {
                out_item->stock_field = mem$new(allc, Stock);
                if (!out_item->stock_field) {
                    return Error.memory;
                }
                e$except_silent (err, serdegen.Stock.deserialize(jr, out_item->stock_field, allc)) {
                    jr->error = err;
                    goto fail;
                }
            } else {
                out_item->stock_field = NULL;
            }

        }
    }
    return EOK;
fail: 
    serdegen.ItemNullable.destroy(out_item, allc);
    return jr->error;
}
void serdegen__ItemNullable__destroy(ItemNullable* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        sbuf.destroy(&item->sbuf_field);
        mem$free(allc, item->str_s_field.buf);
        mem$free(allc, item->char_field);
        serdegen.Stock.destroy(item->stock_field, allc);
        mem$free(allc, item->stock_field);
        memset(item, 0, sizeof(*item));
    }
}

//
// Autogenerated serde for Position type
//
Exception serdegen__Position__serialize(jw_c* jw, Position* item) {
    if (!item) {
        jw$scope(jw, JsonType__null){
            jw$val(NULL);
        }
        return EOK;
    }
    jw$scope(jw, JsonType__obj){
        jw$key("qty");
        jw$val(item->qty);

        jw$key("fill_price");
        jw$val(item->fill_price);

        jw$key("stock");
        e$except_silent (err, serdegen.Stock.serialize(jw, item->stock)) {
            jw->error = err;
        }

    }
    return jw->error;
}
Exc serdegen__Position__print(Position* item, jw_kw* json_writer_kwargs) {
    jw_c jw;
    jw_kw kwargs = {.stream = stdout, .indent = 0};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(_cex_json__writer__create(&jw, &kwargs));
    return serdegen.Position.serialize(&jw, item);
}
Exception serdegen__Position__deserialize(jr_c* jr, Position* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    jr$foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = Error.integrity;
            goto fail;
        } else if (str$eq(k, "qty")) {
            e$except_silent(err, str$convert(v, &out_item->qty)) {
                jr->error = err;
                goto fail;
            }

        } else if (str$eq(k, "fill_price")) {
            e$except_silent(err, str$convert(v, &out_item->fill_price)) {
                jr->error = err;
                goto fail;
            }

        } else if (str$eq(k, "stock")) {
            if (jr->type != JsonType__null) {
                out_item->stock = mem$new(allc, Stock);
                if (!out_item->stock) {
                    return Error.memory;
                }
                e$except_silent (err, serdegen.Stock.deserialize(jr, out_item->stock, allc)) {
                    jr->error = err;
                    goto fail;
                }
            } else {
                out_item->stock = NULL;
            }

        }
    }
    return EOK;
fail: 
    serdegen.Position.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Position__destroy(Position* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        serdegen.Stock.destroy(item->stock, allc);
        mem$free(allc, item->stock);
        memset(item, 0, sizeof(*item));
    }
}

const struct __cex_namespace__serdegen serdegen = {
    // Autogenerated by CEX
    // clang-format off


    .ItemNullable = {
        .deserialize = serdegen__ItemNullable__deserialize,
        .destroy = serdegen__ItemNullable__destroy,
        .print = serdegen__ItemNullable__print,
        .serialize = serdegen__ItemNullable__serialize,
    },

    .Position = {
        .deserialize = serdegen__Position__deserialize,
        .destroy = serdegen__Position__destroy,
        .print = serdegen__Position__print,
        .serialize = serdegen__Position__serialize,
    },

    .Stock = {
        .deserialize = serdegen__Stock__deserialize,
        .destroy = serdegen__Stock__destroy,
        .print = serdegen__Stock__print,
        .serialize = serdegen__Stock__serialize,
    },

    // clang-format on
};
