#pragma once
#include "cex.h"

json$$struct();
typedef struct schema_s {
    char* path;
    f32 factor;
    u32 capacity;
} schema_s;

json$$struct();
typedef struct App_c {
    i32 number;
    char* my_string;

    json$$field(.name = "my_schema");
    schema_s schema;
} App_c;

struct __cex_namespace__App {
    // Autogenerated by CEX
    // clang-format off

    Exception       (*check_args)(App_c* app, i32 argc, char** argv);
    Exception       (*create)(App_c* app, i32 argc, char** argv);
    void            (*destroy)(App_c* app);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__App App;

