#include "cex.h"
#include "App.h"
#include "serde.h"

Exception
App_check_args(App_c* app, i32 argc, char** argv) {
    (void)app;
    (void)argc;
    (void)argv;

    if(argc != 2) {
        return e$raise(Error.argsparse, "Expected JSON file path");
    }

    char* filename = argv[1];
    if(str.len(filename) == 0) {
        return e$raise(Error.argsparse, "Empty json file name");
    }

    if(!str.ends_with(filename, ".json")) {
        return "Expected .json file name";
    }

    if (!os.path.exists(filename)) {
        return e$raise(Error.argsparse, "File name not exists: %s", filename);
    }


    return EOK;
}

Exception
App_create(App_c* app, i32 argc, char** argv) {
    (void)app;

    e$ret(App.check_args(app, argc, argv));

    mem$scope(tmem$, _) {
        char* json_content = io.file.load(argv[1], _);
        uassert(json_content && "No mem or IO error");

        json_rd_c jr = {0};
        e$ret(json$rd_new(&jr, json_content, 0));
        e$ret(serde.App.deserialize(&jr, app, mem$));
    }

    io.printf("App.create() hi argc=%d, program_name=%s!\n", argc, argv[0]);

    io.printf("App_c contents:\n");

    serde$print(app, .indent = 4, .simplified = true);

    io.printf("\n\nApp_c contents: capacity: %d\n", app->schema.capacity);

    return EOK;
}

void
App_destroy(App_c* app) {
    serde.App.destroy(app, mem$);
}

const struct __cex_namespace__App App = {
    // Autogenerated by CEX
    // clang-format off

    .check_args = App_check_args,
    .create = App_create,
    .destroy = App_destroy,

    // clang-format on
};
