// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#pragma once
#include "cex.h"
#include "cexstd/json/json.h"
#include "src/App.h"

/// Generic `serde` type printer using json
/// Example: 
/// serde$print(any_supported_type_pointer, .indent = 0, .simplified = true ); 
#define serde$print(item, kwargs...) \
    _Generic((item), \
        schema_s*: serde.schema.print, \
        App_c*: serde.App.print\
    )(item, &(json_wr_kw) { kwargs })

struct __cex_namespace__serde {
    // Autogenerated by CEX
    // clang-format off


    struct {
        Exception       (*deserialize)(json_rd_c* jr, App_c* out_item, IAllocator allc);
        void            (*destroy)(App_c* item, IAllocator allc);
        Exc             (*print)(App_c* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, App_c* item);
    } App;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, schema_s* out_item, IAllocator allc);
        void            (*destroy)(schema_s* item, IAllocator allc);
        Exc             (*print)(schema_s* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, schema_s* item);
    } schema;

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__serde serde;

