// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#include "serde.h"

//
// Autogenerated serde for schema_s type
//
Exception serde__schema__serialize(json_wr_c* jw, schema_s* item) {
    if (!item) {
        json$wr_scope(jw, JsonType__null){
            json$wr_val(NULL);
        }
        return EOK;
    }
    json$wr_scope(jw, JsonType__obj){
        json$wr_key("path");
        if (unlikely(!item->path)) {
            jw->error = JsonError.null_field;
        }
        json$wr_val(item->path);

        json$wr_key("factor");
        json$wr_val(item->factor);

        json$wr_key("capacity");
        json$wr_val(item->capacity);

        json$wr_key("test_field");
        json$wr_val(item->test_field);

    }
    return jw->error;
}
Exc serde__schema__print(schema_s* item, json_wr_kw* json_writer_kwargs) {
    json_wr_c jw;
    json_wr_kw kwargs = {.stream = stdout, .indent = 0, .simplified = true};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(json.wr.create(&jw, &kwargs));
    if (kwargs.simplified) {
        json.wr.print_val(&jw, "schema_s(");
        Exc err = serde.schema.serialize(&jw, item);
        json.wr.print_val(&jw, "%s%s%s)\n", (err) ? " [error: ": "", (err) ? err : "", (err) ? "]": "" );
        return err;
    } else {
        return serde.schema.serialize(&jw, item);
    }
}
Exception serde__schema__deserialize(json_rd_c* jr, schema_s* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    memset(out_item, 0, sizeof(*out_item));
    u64 fields_mask = 0;
    json$rd_foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = JsonError.parsing;
            goto fail;
        } else if (str$eq(k, "path")) {
            fields_mask |= (1 << 0);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                json$rd_egoto(jr, JsonError.null_field, fail);
            } else {
                str_s out_s = {0};
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_s, allc), fail);
                out_item->path = out_s.buf;
            }
        } else if (str$eq(k, "factor")) {
            fields_mask |= (1 << 1);
            if (!json$rd_is_type_compatible(jr, &out_item->factor)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->factor), fail);
        } else if (str$eq(k, "capacity")) {
            fields_mask |= (1 << 2);
            if (!json$rd_is_type_compatible(jr, &out_item->capacity)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->capacity), fail);
        } else if (str$eq(k, "test_field")) {
            fields_mask |= (1 << 3);
            if (!json$rd_is_type_compatible(jr, &out_item->test_field)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->test_field), fail);
        } else {
            jr->error = JsonError.unknown_field;
            goto fail;
        }
    }
    if (fields_mask != ((1 << 4) - 1)) {
        if (!jr->error) {
            jr->error = JsonError.missing_field;
        }
        goto fail;
    }
    if (!jr->error) {
        return EOK;
    }
fail: 
    serde.schema.destroy(out_item, allc);
    return jr->error;
}
void serde__schema__destroy(schema_s* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        mem$free(allc, item->path);
        memset(item, 0, sizeof(*item));
    }
}

//
// Autogenerated serde for App_c type
//
Exception serde__App__serialize(json_wr_c* jw, App_c* item) {
    if (!item) {
        json$wr_scope(jw, JsonType__null){
            json$wr_val(NULL);
        }
        return EOK;
    }
    json$wr_scope(jw, JsonType__obj){
        json$wr_key("number");
        json$wr_val(item->number);

        json$wr_key("my_string");
        if (unlikely(!item->my_string)) {
            jw->error = JsonError.null_field;
        }
        json$wr_val(item->my_string);

        json$wr_key("my_schema");
        e$except_silent (err, serde.schema.serialize(jw, &item->schema)) {
            jw->error = err;
        }

    }
    return jw->error;
}
Exc serde__App__print(App_c* item, json_wr_kw* json_writer_kwargs) {
    json_wr_c jw;
    json_wr_kw kwargs = {.stream = stdout, .indent = 0, .simplified = true};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(json.wr.create(&jw, &kwargs));
    if (kwargs.simplified) {
        json.wr.print_val(&jw, "App_c(");
        Exc err = serde.App.serialize(&jw, item);
        json.wr.print_val(&jw, "%s%s%s)\n", (err) ? " [error: ": "", (err) ? err : "", (err) ? "]": "" );
        return err;
    } else {
        return serde.App.serialize(&jw, item);
    }
}
Exception serde__App__deserialize(json_rd_c* jr, App_c* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    memset(out_item, 0, sizeof(*out_item));
    u64 fields_mask = 0;
    json$rd_foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = JsonError.parsing;
            goto fail;
        } else if (str$eq(k, "number")) {
            fields_mask |= (1 << 0);
            if (!json$rd_is_type_compatible(jr, &out_item->number)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->number), fail);
        } else if (str$eq(k, "my_string")) {
            fields_mask |= (1 << 1);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                json$rd_egoto(jr, JsonError.null_field, fail);
            } else {
                str_s out_s = {0};
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_s, allc), fail);
                out_item->my_string = out_s.buf;
            }
        } else if (str$eq(k, "my_schema")) {
            fields_mask |= (1 << 2);
            if (jr->type != JsonType__null) {
                if (jr->type != JsonType__obj) {
                    json$rd_egoto(jr, JsonError.wrong_type, fail);
                }
                json$rd_egoto(jr, serde.schema.deserialize(jr, &out_item->schema, allc), fail);
            } else {
                json$rd_egoto(jr, JsonError.null_field, fail);
            }
        } else {
            jr->error = JsonError.unknown_field;
            goto fail;
        }
    }
    if (fields_mask != ((1 << 3) - 1)) {
        if (!jr->error) {
            jr->error = JsonError.missing_field;
        }
        goto fail;
    }
    if (!jr->error) {
        return EOK;
    }
fail: 
    serde.App.destroy(out_item, allc);
    return jr->error;
}
void serde__App__destroy(App_c* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        mem$free(allc, item->my_string);
        serde.schema.destroy(&item->schema, allc);
        memset(item, 0, sizeof(*item));
    }
}

CEX_NAMESPACE_DEF struct __cex_namespace__serde serde = {
    // Autogenerated by CEX
    // clang-format off


    .App = {
        .deserialize = serde__App__deserialize,
        .destroy = serde__App__destroy,
        .print = serde__App__print,
        .serialize = serde__App__serialize,
    },

    .schema = {
        .deserialize = serde__schema__deserialize,
        .destroy = serde__schema__destroy,
        .print = serde__schema__print,
        .serialize = serde__schema__serialize,
    },

    // clang-format on
};
