#include "mylib.h"
#include "cex.h"

Exception mylib_create(mylib_c* self, i32 base_num){
    *self = (mylib_c){.base_num = base_num};
    return EOK;
}

i32 mylib_add(mylib_c* self, i32 a, i32 b){
    return a + b + self->base_num;
}

struct __cex_namespace__mylib mylib = {
    // Autogenerated by CEX
    // clang-format off

    .add = mylib_add,
    .create = mylib_create,

    // clang-format on
};
