#pragma once
#include "cex.h"


typedef struct mylib_c {
    i32 base_num;
} mylib_c;

struct __cex_namespace__mylib {
    // Autogenerated by CEX
    // clang-format off

    i32             (*add)(mylib_c* self, i32 a, i32 b);
    Exception       (*create)(mylib_c* self, i32 base_num);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__mylib mylib;

