// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#include "serdegen.h"

//
// Autogenerated serde for Stock type
//
Exception serdegen__Stock__serialize(json_wr_c* jw, Stock* item) {
    if (!item) {
        json$wr_scope(jw, JsonType__null){
            json$wr_val(NULL);
        }
        return EOK;
    }
    json$wr_scope(jw, JsonType__obj){
        json$wr_key("id");
        json$wr_val(item->id);

        json$wr_key("ticker");
        // field `ticker` is nullable json$$field(.nullable = true)
        json$wr_val(item->ticker);

        json$wr_key("exchange");
        // field `exchange` is nullable json$$field(.nullable = true)
        json$wr_val(item->exchange);

    }
    return jw->error;
}
Exc serdegen__Stock__print(Stock* item, json_wr_kw* json_writer_kwargs) {
    json_wr_c jw;
    json_wr_kw kwargs = {.stream = stdout, .indent = 0, .simplified = true};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(json.wr.create(&jw, &kwargs));
    if (kwargs.simplified) {
        json.wr.print_val(&jw, "Stock(");
        Exc err = serdegen.Stock.serialize(&jw, item);
        json.wr.print_val(&jw, "%s%s%s)\n", (err) ? " [error: ": "", (err) ? err : "", (err) ? "]": "" );
        return err;
    } else {
        return serdegen.Stock.serialize(&jw, item);
    }
}
Exception serdegen__Stock__deserialize(json_rd_c* jr, Stock* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    u64 fields_mask = 0;
    json$rd_foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = JsonError.parsing;
            goto fail;
        } else if (str$eq(k, "id")) {
            fields_mask |= (1 << 0);
            if (!json$rd_is_type_compatible(jr, &out_item->id)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->id), fail);
        } else if (str$eq(k, "ticker")) {
            // fields_mask check skipped, field is json$$field(.optional = true)
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                // field `ticker` is nullable json$$field(.nullable = true)
                out_item->ticker = NULL;
            } else {
                str_s out_s = {0};
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_s, allc), fail);
                out_item->ticker = out_s.buf;
            }
        } else if (str$eq(k, "exchange")) {
            fields_mask |= (1 << 1);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                // field `exchange` is nullable json$$field(.nullable = true)
                out_item->exchange = NULL;
            } else {
                str_s out_s = {0};
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_s, allc), fail);
                out_item->exchange = out_s.buf;
            }
        } else {
            jr->error = JsonError.unknown_field;
            goto fail;
        }
    }
    if (fields_mask != ((1 << 2) - 1)) {
        if (!jr->error) {
            jr->error = JsonError.missing_field;
        }
        goto fail;
    }
    if (!jr->error) {
        return EOK;
    }
fail: 
    serdegen.Stock.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Stock__destroy(Stock* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        mem$free(allc, item->ticker);
        mem$free(allc, item->exchange);
        memset(item, 0, sizeof(*item));
    }
}

//
// Autogenerated serde for ItemNullable type
//
Exception serdegen__ItemNullable__serialize(json_wr_c* jw, ItemNullable* item) {
    if (!item) {
        json$wr_scope(jw, JsonType__null){
            json$wr_val(NULL);
        }
        return EOK;
    }
    json$wr_scope(jw, JsonType__obj){
        json$wr_key("sbuf_field");
        // field `sbuf_field` is nullable json$$field(.nullable = true)
        json$wr_val(item->sbuf_field);

        json$wr_key("str_s_field");
        // field `str_s_field` is nullable json$$field(.nullable = true)
        json$wr_val(item->str_s_field);

        json$wr_key("char_field");
        // field `char_field` is nullable json$$field(.nullable = true)
        json$wr_val(item->char_field);

        json$wr_key("stock_field");
        // field `stock_field` is nullable json$$field(.nullable = true)
        e$except_silent (err, serdegen.Stock.serialize(jw, item->stock_field)) {
            jw->error = err;
        }

        json$wr_key("stock_val");
        // field `stock_val` is nullable json$$field(.nullable = true)
        e$except_silent (err, serdegen.Stock.serialize(jw, &item->stock_val)) {
            jw->error = err;
        }

    }
    return jw->error;
}
Exc serdegen__ItemNullable__print(ItemNullable* item, json_wr_kw* json_writer_kwargs) {
    json_wr_c jw;
    json_wr_kw kwargs = {.stream = stdout, .indent = 0, .simplified = true};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(json.wr.create(&jw, &kwargs));
    if (kwargs.simplified) {
        json.wr.print_val(&jw, "ItemNullable(");
        Exc err = serdegen.ItemNullable.serialize(&jw, item);
        json.wr.print_val(&jw, "%s%s%s)\n", (err) ? " [error: ": "", (err) ? err : "", (err) ? "]": "" );
        return err;
    } else {
        return serdegen.ItemNullable.serialize(&jw, item);
    }
}
Exception serdegen__ItemNullable__deserialize(json_rd_c* jr, ItemNullable* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    u64 fields_mask = 0;
    json$rd_foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = JsonError.parsing;
            goto fail;
        } else if (str$eq(k, "sbuf_field")) {
            fields_mask |= (1 << 0);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                // field `sbuf_field` is nullable json$$field(.nullable = true)
                out_item->sbuf_field = NULL;
            } else {
                out_item->sbuf_field = sbuf.create(v.len + sizeof(sbuf_head_s) + 1, allc);
                if (unlikely(!out_item->sbuf_field)) {
                    return Error.memory;
                }
                usize out_buf_len = v.len + 1;
                json$rd_egoto(jr, json$rd_str_unescape_inplace(v, out_item->sbuf_field, &out_buf_len), fail);
                json$rd_egoto(jr, sbuf.set_len(&out_item->sbuf_field, out_buf_len), fail);
            }
        } else if (str$eq(k, "str_s_field")) {
            fields_mask |= (1 << 1);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                // field `str_s_field` is nullable json$$field(.nullable = true)
                out_item->str_s_field = (str_s){0};
            } else {
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_item->str_s_field, allc), fail);
            }
        } else if (str$eq(k, "char_field")) {
            fields_mask |= (1 << 2);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                // field `char_field` is nullable json$$field(.nullable = true)
                out_item->char_field = NULL;
            } else {
                str_s out_s = {0};
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_s, allc), fail);
                out_item->char_field = out_s.buf;
            }
        } else if (str$eq(k, "stock_field")) {
            fields_mask |= (1 << 3);
            if (jr->type != JsonType__null) {
                if (jr->type != JsonType__obj) {
                    json$rd_egoto(jr, JsonError.wrong_type, fail);
                }
                out_item->stock_field = mem$new(allc, Stock);
                if (!out_item->stock_field) {
                    return Error.memory;
                }
                json$rd_egoto(jr, serdegen.Stock.deserialize(jr, out_item->stock_field, allc), fail);
            } else {
                // field `stock_field` is nullable json$$field(.nullable = true)
                out_item->stock_field = NULL;
            }
        } else if (str$eq(k, "stock_val")) {
            fields_mask |= (1 << 4);
            if (jr->type != JsonType__null) {
                if (jr->type != JsonType__obj) {
                    json$rd_egoto(jr, JsonError.wrong_type, fail);
                }
                json$rd_egoto(jr, serdegen.Stock.deserialize(jr, &out_item->stock_val, allc), fail);
            } else {
                json$rd_egoto(jr, JsonError.null_field, fail);
            }
        } else {
            jr->error = JsonError.unknown_field;
            goto fail;
        }
    }
    if (fields_mask != ((1 << 5) - 1)) {
        if (!jr->error) {
            jr->error = JsonError.missing_field;
        }
        goto fail;
    }
    if (!jr->error) {
        return EOK;
    }
fail: 
    serdegen.ItemNullable.destroy(out_item, allc);
    return jr->error;
}
void serdegen__ItemNullable__destroy(ItemNullable* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        sbuf.destroy(&item->sbuf_field);
        mem$free(allc, item->str_s_field.buf);
        mem$free(allc, item->char_field);
        serdegen.Stock.destroy(item->stock_field, allc);
        mem$free(allc, item->stock_field);
        serdegen.Stock.destroy(&item->stock_val, allc);
        memset(item, 0, sizeof(*item));
    }
}

//
// Autogenerated serde for Item type
//
Exception serdegen__Item__serialize(json_wr_c* jw, Item* item) {
    if (!item) {
        json$wr_scope(jw, JsonType__null){
            json$wr_val(NULL);
        }
        return EOK;
    }
    json$wr_scope(jw, JsonType__obj){
        json$wr_key("sbuf_field");
        if (unlikely(!item->sbuf_field)) {
            jw->error = JsonError.null_field;
        }
        json$wr_val(item->sbuf_field);

        json$wr_key("str_s_field");
        if (unlikely(!item->str_s_field.buf)) {
            jw->error = JsonError.null_field;
        }
        json$wr_val(item->str_s_field);

        json$wr_key("char_field");
        if (unlikely(!item->char_field)) {
            jw->error = JsonError.null_field;
        }
        json$wr_val(item->char_field);

        json$wr_key("stock_field");
        if (unlikely(!item->stock_field)) {
            jw->error = JsonError.null_field;
        }
        e$except_silent (err, serdegen.Stock.serialize(jw, item->stock_field)) {
            jw->error = err;
        }

        // field `stock_field_skipped` is skipped json$$field(.skip = true)
    }
    return jw->error;
}
Exc serdegen__Item__print(Item* item, json_wr_kw* json_writer_kwargs) {
    json_wr_c jw;
    json_wr_kw kwargs = {.stream = stdout, .indent = 0, .simplified = true};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(json.wr.create(&jw, &kwargs));
    if (kwargs.simplified) {
        json.wr.print_val(&jw, "Item(");
        Exc err = serdegen.Item.serialize(&jw, item);
        json.wr.print_val(&jw, "%s%s%s)\n", (err) ? " [error: ": "", (err) ? err : "", (err) ? "]": "" );
        return err;
    } else {
        return serdegen.Item.serialize(&jw, item);
    }
}
Exception serdegen__Item__deserialize(json_rd_c* jr, Item* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    u64 fields_mask = 0;
    json$rd_foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = JsonError.parsing;
            goto fail;
        } else if (str$eq(k, "sbuf_field")) {
            fields_mask |= (1 << 0);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                json$rd_egoto(jr, JsonError.null_field, fail);
            } else {
                out_item->sbuf_field = sbuf.create(v.len + sizeof(sbuf_head_s) + 1, allc);
                if (unlikely(!out_item->sbuf_field)) {
                    return Error.memory;
                }
                usize out_buf_len = v.len + 1;
                json$rd_egoto(jr, json$rd_str_unescape_inplace(v, out_item->sbuf_field, &out_buf_len), fail);
                json$rd_egoto(jr, sbuf.set_len(&out_item->sbuf_field, out_buf_len), fail);
            }
        } else if (str$eq(k, "str_s_field")) {
            fields_mask |= (1 << 1);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                json$rd_egoto(jr, JsonError.null_field, fail);
            } else {
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_item->str_s_field, allc), fail);
            }
        } else if (str$eq(k, "char_field")) {
            fields_mask |= (1 << 2);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                json$rd_egoto(jr, JsonError.null_field, fail);
            } else {
                str_s out_s = {0};
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_s, allc), fail);
                out_item->char_field = out_s.buf;
            }
        } else if (str$eq(k, "stock_field")) {
            fields_mask |= (1 << 3);
            if (jr->type != JsonType__null) {
                if (jr->type != JsonType__obj) {
                    json$rd_egoto(jr, JsonError.wrong_type, fail);
                }
                out_item->stock_field = mem$new(allc, Stock);
                if (!out_item->stock_field) {
                    return Error.memory;
                }
                json$rd_egoto(jr, serdegen.Stock.deserialize(jr, out_item->stock_field, allc), fail);
            } else {
                json$rd_egoto(jr, JsonError.null_field, fail);
            }
        }
        // field `stock_field_skipped` is skipped json$$field(.skip = true)
        else {
            jr->error = JsonError.unknown_field;
            goto fail;
        }
    }
    if (fields_mask != ((1 << 4) - 1)) {
        if (!jr->error) {
            jr->error = JsonError.missing_field;
        }
        goto fail;
    }
    if (!jr->error) {
        return EOK;
    }
fail: 
    serdegen.Item.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Item__destroy(Item* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        sbuf.destroy(&item->sbuf_field);
        mem$free(allc, item->str_s_field.buf);
        mem$free(allc, item->char_field);
        serdegen.Stock.destroy(item->stock_field, allc);
        mem$free(allc, item->stock_field);
        serdegen.Stock.destroy(item->stock_field_skipped, allc);
        mem$free(allc, item->stock_field_skipped);
        memset(item, 0, sizeof(*item));
    }
}

//
// Autogenerated serde for Order type
//
Exception serdegen__Order__serialize(json_wr_c* jw, Order* item) {
    if (!item) {
        json$wr_scope(jw, JsonType__null){
            json$wr_val(NULL);
        }
        return EOK;
    }
    json$wr_scope(jw, JsonType__obj){
        json$wr_key("id");
        json$wr_val(item->id);

        json$wr_key("price");
        json$wr_val(item->price);

        json$wr_key("qty");
        json$wr_val(item->qty);

        json$wr_key("is_active");
        json$wr_val(item->is_active);

        json$wr_key("exchange");
        if (unlikely(!item->exchange)) {
            jw->error = JsonError.null_field;
        }
        json$wr_val(item->exchange);

        json$wr_key("stock");
        if (unlikely(!item->stock)) {
            jw->error = JsonError.null_field;
        }
        e$except_silent (err, serdegen.Stock.serialize(jw, item->stock)) {
            jw->error = err;
        }

    }
    return jw->error;
}
Exc serdegen__Order__print(Order* item, json_wr_kw* json_writer_kwargs) {
    json_wr_c jw;
    json_wr_kw kwargs = {.stream = stdout, .indent = 0, .simplified = true};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(json.wr.create(&jw, &kwargs));
    if (kwargs.simplified) {
        json.wr.print_val(&jw, "Order(");
        Exc err = serdegen.Order.serialize(&jw, item);
        json.wr.print_val(&jw, "%s%s%s)\n", (err) ? " [error: ": "", (err) ? err : "", (err) ? "]": "" );
        return err;
    } else {
        return serdegen.Order.serialize(&jw, item);
    }
}
Exception serdegen__Order__deserialize(json_rd_c* jr, Order* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    u64 fields_mask = 0;
    json$rd_foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = JsonError.parsing;
            goto fail;
        } else if (str$eq(k, "id")) {
            fields_mask |= (1 << 0);
            if (!json$rd_is_type_compatible(jr, &out_item->id)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->id), fail);
        } else if (str$eq(k, "price")) {
            fields_mask |= (1 << 1);
            if (!json$rd_is_type_compatible(jr, &out_item->price)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->price), fail);
        } else if (str$eq(k, "qty")) {
            fields_mask |= (1 << 2);
            if (!json$rd_is_type_compatible(jr, &out_item->qty)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->qty), fail);
        } else if (str$eq(k, "is_active")) {
            fields_mask |= (1 << 3);
            if (!json$rd_is_type_compatible(jr, &out_item->is_active)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->is_active), fail);
        } else if (str$eq(k, "exchange")) {
            fields_mask |= (1 << 4);
            if (jr->type != JsonType__str && jr->type != JsonType__null) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            if (unlikely(!v.buf)) {
                json$rd_egoto(jr, JsonError.null_field, fail);
            } else {
                str_s out_s = {0};
                json$rd_egoto(jr, json$rd_str_unescape(v, &out_s, allc), fail);
                out_item->exchange = out_s.buf;
            }
        } else if (str$eq(k, "stock")) {
            fields_mask |= (1 << 5);
            if (jr->type != JsonType__null) {
                if (jr->type != JsonType__obj) {
                    json$rd_egoto(jr, JsonError.wrong_type, fail);
                }
                out_item->stock = mem$new(allc, Stock);
                if (!out_item->stock) {
                    return Error.memory;
                }
                json$rd_egoto(jr, serdegen.Stock.deserialize(jr, out_item->stock, allc), fail);
            } else {
                json$rd_egoto(jr, JsonError.null_field, fail);
            }
        } else {
            jr->error = JsonError.unknown_field;
            goto fail;
        }
    }
    if (fields_mask != ((1 << 6) - 1)) {
        if (!jr->error) {
            jr->error = JsonError.missing_field;
        }
        goto fail;
    }
    if (!jr->error) {
        return EOK;
    }
fail: 
    serdegen.Order.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Order__destroy(Order* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        mem$free(allc, item->exchange);
        serdegen.Stock.destroy(item->stock, allc);
        mem$free(allc, item->stock);
        memset(item, 0, sizeof(*item));
    }
}

//
// Autogenerated serde for Position type
//
Exception serdegen__Position__serialize(json_wr_c* jw, Position* item) {
    if (!item) {
        json$wr_scope(jw, JsonType__null){
            json$wr_val(NULL);
        }
        return EOK;
    }
    json$wr_scope(jw, JsonType__obj){
        json$wr_key("qty");
        json$wr_val(item->qty);

        json$wr_key("fill_price");
        json$wr_val(item->fill_price);

        json$wr_key("stock");
        if (unlikely(!item->stock)) {
            jw->error = JsonError.null_field;
        }
        e$except_silent (err, serdegen.Stock.serialize(jw, item->stock)) {
            jw->error = err;
        }

    }
    return jw->error;
}
Exc serdegen__Position__print(Position* item, json_wr_kw* json_writer_kwargs) {
    json_wr_c jw;
    json_wr_kw kwargs = {.stream = stdout, .indent = 0, .simplified = true};
    if (json_writer_kwargs) {
        kwargs = *json_writer_kwargs;
        if (!kwargs.stream && !kwargs.buf) {
            kwargs.stream = stdout;
        }
    }
    e$ret(json.wr.create(&jw, &kwargs));
    if (kwargs.simplified) {
        json.wr.print_val(&jw, "Position(");
        Exc err = serdegen.Position.serialize(&jw, item);
        json.wr.print_val(&jw, "%s%s%s)\n", (err) ? " [error: ": "", (err) ? err : "", (err) ? "]": "" );
        return err;
    } else {
        return serdegen.Position.serialize(&jw, item);
    }
}
Exception serdegen__Position__deserialize(json_rd_c* jr, Position* out_item, IAllocator allc) {
    uassert(jr != NULL);
    uassert(out_item != NULL);
    u64 fields_mask = 0;
    json$rd_foreach(k, v, jr) {
        if (!k.buf) {
            jr->error = JsonError.parsing;
            goto fail;
        } else if (str$eq(k, "qty")) {
            fields_mask |= (1 << 0);
            if (!json$rd_is_type_compatible(jr, &out_item->qty)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->qty), fail);
        } else if (str$eq(k, "fill_price")) {
            fields_mask |= (1 << 1);
            if (!json$rd_is_type_compatible(jr, &out_item->fill_price)) {
                json$rd_egoto(jr, JsonError.wrong_type, fail);
            }
            json$rd_egoto(jr, str$convert(v, &out_item->fill_price), fail);
        } else if (str$eq(k, "stock")) {
            fields_mask |= (1 << 2);
            if (jr->type != JsonType__null) {
                if (jr->type != JsonType__obj) {
                    json$rd_egoto(jr, JsonError.wrong_type, fail);
                }
                out_item->stock = mem$new(allc, Stock);
                if (!out_item->stock) {
                    return Error.memory;
                }
                json$rd_egoto(jr, serdegen.Stock.deserialize(jr, out_item->stock, allc), fail);
            } else {
                json$rd_egoto(jr, JsonError.null_field, fail);
            }
        } else {
            jr->error = JsonError.unknown_field;
            goto fail;
        }
    }
    if (fields_mask != ((1 << 3) - 1)) {
        if (!jr->error) {
            jr->error = JsonError.missing_field;
        }
        goto fail;
    }
    if (!jr->error) {
        return EOK;
    }
fail: 
    serdegen.Position.destroy(out_item, allc);
    return jr->error;
}
void serdegen__Position__destroy(Position* item, IAllocator allc) {
    uassert(allc != NULL);
    if (item) {
        serdegen.Stock.destroy(item->stock, allc);
        mem$free(allc, item->stock);
        memset(item, 0, sizeof(*item));
    }
}

const struct __cex_namespace__serdegen serdegen = {
    // Autogenerated by CEX
    // clang-format off


    .ItemNullable = {
        .deserialize = serdegen__ItemNullable__deserialize,
        .destroy = serdegen__ItemNullable__destroy,
        .print = serdegen__ItemNullable__print,
        .serialize = serdegen__ItemNullable__serialize,
    },

    .Item = {
        .deserialize = serdegen__Item__deserialize,
        .destroy = serdegen__Item__destroy,
        .print = serdegen__Item__print,
        .serialize = serdegen__Item__serialize,
    },

    .Order = {
        .deserialize = serdegen__Order__deserialize,
        .destroy = serdegen__Order__destroy,
        .print = serdegen__Order__print,
        .serialize = serdegen__Order__serialize,
    },

    .Position = {
        .deserialize = serdegen__Position__deserialize,
        .destroy = serdegen__Position__destroy,
        .print = serdegen__Position__print,
        .serialize = serdegen__Position__serialize,
    },

    .Stock = {
        .deserialize = serdegen__Stock__deserialize,
        .destroy = serdegen__Stock__destroy,
        .print = serdegen__Stock__print,
        .serialize = serdegen__Stock__serialize,
    },

    // clang-format on
};
