// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#include "cex.h"
#include "cexstd/json/json.h"
#include "tests/cexstd/json//advanced/AdvStock.h"
#include "tests/cexstd/json//advanced/AdvPosition.h"

struct __cex_namespace__serdegen {
    // Autogenerated by CEX
    // clang-format off


    struct {
        Exception       (*deserialize)(json_rd_c* jr, ItemNullable* out_item, IAllocator allc);
        void            (*destroy)(ItemNullable* item, IAllocator allc);
        Exc             (*print)(ItemNullable* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, ItemNullable* item);
    } ItemNullable;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, Item* out_item, IAllocator allc);
        void            (*destroy)(Item* item, IAllocator allc);
        Exc             (*print)(Item* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Item* item);
    } Item;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, Order2* out_item, IAllocator allc);
        void            (*destroy)(Order2* item, IAllocator allc);
        Exc             (*print)(Order2* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Order2* item);
    } Order2;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, Order* out_item, IAllocator allc);
        void            (*destroy)(Order* item, IAllocator allc);
        Exc             (*print)(Order* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Order* item);
    } Order;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, Position* out_item, IAllocator allc);
        void            (*destroy)(Position* item, IAllocator allc);
        Exc             (*print)(Position* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Position* item);
    } Position;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, Stock* out_item, IAllocator allc);
        void            (*destroy)(Stock* item, IAllocator allc);
        Exc             (*print)(Stock* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Stock* item);
    } Stock;

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__serdegen serdegen;

