#pragma once
#include "cex/cexlib/sview.h"
#include <cex/cex.h>
#include <stdio.h>


typedef struct io_c
{
    FILE* _fh;
    size_t _fsize;
    char* _fbuf;
    size_t _fbuf_size;
    const Allocator_c* _allocator;
    struct
    {
        u32 is_attached : 1;

    } _flags;
} io_c;


struct __module__io
{
    // Autogenerated by CEX
    // clang-format off

Exception
(*fopen)(io_c* self, const char* filename, const char* mode, const Allocator_c* allocator);

Exception
(*fattach)(io_c* self, FILE* fh, const Allocator_c* allocator);

size_t
(*size)(io_c* self);

Exception
(*readall)(io_c* self, sview_c* s);

void
(*close)(io_c* self);

    // clang-format on
};
extern const struct __module__io io; // CEX Autogen
