#pragma once
#include "cex.h"

struct __cex_namespace__mylib {
    // Autogenerated by CEX
    // clang-format off

    i32             (*add)(i32 a, u32 b);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__mylib mylib;

