#include "mylib.h"
#include "cex.h"

i32 mylib_add(i32 a, u32 b){
    return a + b;
}

CEX_NAMESPACE_DEF struct __cex_namespace__mylib mylib = {
    // Autogenerated by CEX
    // clang-format off

    .add = mylib_add,

    // clang-format on
};
