#include "cex.h"

struct __cex_namespace__nstest {
    // Autogenerated by CEX
    // clang-format off

    void            (*barNaz)(void);
    void            (*bar_baz)(void);
    void            (*foo_fun)(void);

    struct {
        void            (*foo)(void);
        void            (*foo2)(void);
    } foo_bar;

    struct {
        void            (*_foo)(void);
        void            (*foo)(void);
    } foo;

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__nstest nstest;

