#include "nstest.h"

static void
nstest_foo_fun(void) {
    // nstest.foo
}

static void
nstest_bar_baz(void) {
    // nstest.bar_baz
}

static void
nstest_barNaz(void) {
    // nstest.barNaz
}

static void
nstest__foo__foo(void) {
    // nstest.foo.foo
}

static void
nstest__foo___foo(void) {
    // nstest.foo._foo
}

static void
cex_nstest__foo_bar__foo2(void) {
    // nstest.foo_bar.foo
}

static void
cex_nstest__foo_bar__foo(void) {
    // nstest.foo_bar.foo
}

static void
_cex_nstest_private_hidden(void) {
    // Must be excluded
}

static void
cex_nstest_private_hidden_(void) {
    // Must be excluded
}

static inline void
cex_nstest_inline_excluded(void) {
    // Must be excluded
}

CEX_NAMESPACE_DEF struct __cex_namespace__nstest nstest = {
    // Autogenerated by CEX
    // clang-format off

    .barNaz = nstest_barNaz,
    .bar_baz = nstest_bar_baz,
    .foo_fun = nstest_foo_fun,

    .foo_bar = {
        .foo = cex_nstest__foo_bar__foo,
        .foo2 = cex_nstest__foo_bar__foo2,
    },

    .foo = {
        ._foo = nstest__foo___foo,
        .foo = nstest__foo__foo,
    },

    // clang-format on
};
