#include "myserde.h"

Exception
myserde__Stock__deserialize(jr_c* jr, Stock* out_item, IAllocator allc)
{
    uassert(jr != NULL);

    jr$foreach(k, v, jr)
    {
        if (str$eq(k, "id")) {
            jr$egoto(jr, str$convert(v, &out_item->id), fail);
        } else if (str$eq(k, "ticker")) {
            out_item->ticker = str.slice.clone(v, allc);
            if (!out_item->ticker) {
                jr->error = Error.memory;
                goto fail;
            }
        } else if (str$eq(k, "exchange")) {
            out_item->exchange = str.slice.clone(v, allc);
            if (!out_item->exchange) { jr$egoto(jr, Error.memory, fail); }
        }
    }
    return EOK;

fail:
    myserde.Stock.destroy(out_item, allc);
    return jr->error;
}

void
myserde__Stock__destroy(Stock* item, IAllocator allc)
{
    uassert(allc);

    if (item) {
        mem$free(allc, item->ticker);
        mem$free(allc, item->exchange);
        memset(item, 0, sizeof(*item));
    }
}

Exception
myserde__Stock__serialize(jw_c* jw, Stock* item, jw_kw* json_writer_kwargs)
{
    (void)json_writer_kwargs;
    uassert(jw != NULL);

    jw$scope(jw, JsonType__obj)
    {
        jw$key("id");
        jw$val(item->id);

        jw$key("ticker");
        jw$val(item->ticker);

        jw$key("exchange");
        jw$val(item->exchange);
    }

    return jw->error;
}

Exc
myserde__Stock__print(Stock* item, jw_kw* json_writer_kwargs)
{
    (void)json_writer_kwargs;
    jw_c jw;
    e$ret(jw$new(&jw, .stream = stdout, .indent = 0));
    return myserde__Stock__serialize(&jw, item, NULL);
}

Exception
myserde__Position__serialize(jw_c* jw, Position* item, jw_kw* json_writer_kwargs)
{
    (void)json_writer_kwargs;
    uassert(jw != NULL);

    jw$scope(jw, JsonType__obj)
    {
        jw$key("qty");
        jw$val(item->qty);

        jw$key("fill_price");
        jw$fmt("%0.2f", item->fill_price);

        jw$key("stock");
        e$except_silent (err, myserde.Stock.serialize(jw, item->stock, json_writer_kwargs)) {
            jw->error = err;
        }
    }

    return jw->error;
}

Exc
myserde__Position__print(Position* item, jw_kw* json_writer_kwargs)
{
    (void)json_writer_kwargs;
    jw_c jw;
    e$ret(jw$new(&jw, .stream = stdout, .indent = 0));
    return myserde__Position__serialize(&jw, item, NULL);
}

Exception
myserde__Position__deserialize(jr_c* jr, Position* out_item, IAllocator allc)
{
    uassert(jr != NULL);

    jr$foreach(k, v, jr)
    {
        if (str$eq(k, "qty")) {
            jr$egoto(jr, str$convert(v, &out_item->qty), fail);
        } else if (str$eq(k, "fill_price")) {
            jr$egoto(jr, str$convert(v, &out_item->fill_price), fail);
        } else if (str$eq(k, "stock")) {
            out_item->stock = mem$new(allc, Stock);
            if (!out_item->stock) { jr$egoto(jr, Error.memory, fail); }
            jr$egoto(jr, myserde.Stock.deserialize(jr, out_item->stock, allc), fail);
        }
    }
    return EOK;

fail:
    myserde.Position.destroy(out_item, allc);
    return jr->error;
}

void
myserde__Position__destroy(Position* item, IAllocator allc)
{
    uassert(allc);

    if (item) {
        myserde.Stock.destroy(item->stock, allc);
        if (item->stock) {
            mem$free(allc, item->stock);
        }
        memset(item, 0, sizeof(*item));
    }
}

const struct __cex_namespace__myserde myserde = {
    // Autogenerated by CEX
    // clang-format off


    .Position = {
        .deserialize = myserde__Position__deserialize,
        .destroy = myserde__Position__destroy,
        .print = myserde__Position__print,
        .serialize = myserde__Position__serialize,
    },

    .Stock = {
        .deserialize = myserde__Stock__deserialize,
        .destroy = myserde__Stock__destroy,
        .print = myserde__Stock__print,
        .serialize = myserde__Stock__serialize,
    },

    // clang-format on
};
