#include "cex.h"
#include "lib/json/json.h"

/// Hi this is my comment
serde$$struct(.name = "MyStock")
typedef struct Stock {
    u64 id;
    char* ticker;
    char* exchange;

    serde$$field(.name = "my_json_name", .skip = true)
    char* my_field;
} Stock;

serde$$struct()
typedef struct Position {
    i32 qty;
    f32 fill_price;
    Stock* stock;
} Position;

struct __cex_namespace__myserde {
    // Autogenerated by CEX
    // clang-format off


    struct {
        Exception       (*deserialize)(jr_c* jr, Position* out_item, IAllocator allc);
        void            (*destroy)(Position* item, IAllocator allc);
        Exc             (*print)(Position* item, jw_kw* json_writer_kwargs);
        Exception       (*serialize)(jw_c* jw, Position* item, jw_kw* json_writer_kwargs);
    } Position;

    struct {
        Exception       (*deserialize)(jr_c* jr, Stock* out_item, IAllocator allc);
        void            (*destroy)(Stock* item, IAllocator allc);
        Exc             (*print)(Stock* item, jw_kw* json_writer_kwargs);
        Exception       (*serialize)(jw_c* jw, Stock* item, jw_kw* json_writer_kwargs);
    } Stock;

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__myserde myserde;

