#include <cex.h>

#ifdef _WIN32
#include "_os_win.c"
#else
#include "_os_posix.c"
#endif

Exception
os_listdir(str_c path, sbuf_c* out, const Allocator_i* allc)
{
    return os__listdir(path, out, allc);
}

const struct __module__os os = {
    // Autogenerated by CEX
    // clang-format off
    .listdir = os_listdir,
    // clang-format on
};