#include <cex.h>

#ifdef _WIN32
#include "_os_win.c"
#else
#include "_os_posix.c"
#endif

Exception
os_listdir(str_c path, sbuf_c* out)
{
    return os__listdir(path, out);
}

Exception
os_getcwd(sbuf_c* out){
   return os__getcwd(out);
}

const struct __module__os os = {
    // Autogenerated by CEX
    // clang-format off
    .listdir = os_listdir,
    .getcwd = os_getcwd,
    // clang-format on
};