#include <cex.h>


struct __module__os
{
    // Autogenerated by CEX
    // clang-format off

Exception
(*listdir)(str_c path, sbuf_c* out, const Allocator_i* allc);

    // clang-format on
};
extern const struct __module__os os; // CEX Autogen
