#pragma once
#include "cex.h"

typedef struct App_c {
    u32 argc;           
    const char* path;
} App_c;

struct __class__App
{
    // Autogenerated by CEX
    // clang-format off

Exception
(*create)(App_c* app, i32 argc, char* argv[], const Allocator_i* allocator);

Exception
(*main)(App_c* app, const Allocator_i* allocator);

void
(*destroy)(App_c* app, const Allocator_i* allocator);

    // clang-format on
};
extern const struct __class__App App; // CEX Autogen
