#include "App.h"
#include "cex.h"

Exception
App_create(App_c* app, i32 argc, char* argv[], const Allocator_i* allocator)
{
  utracef("App_init app\n");

  argparse_opt_s options[] = {
    argparse$opt_help(),
    argparse$opt_group("Basic options"),
    argparse$opt_string(
      'p', "path", &app->path, "path to read", .required = true, NULL, 0, 0),
  };

  const char* usage = "basic [options] [[--] args]\n"
                      "basic [options]\n";

  argparse_c args = { .options = options,
                      .options_len = arr$len(options),
                      .usage = usage,
                      .description = "A cool CEX program",
                      .epilog = "help epilog text here" };

  // NOTE: there is no need to traceback here, because argparse.parse() prints
  except(err, argparse.parse(&args, argc, argv)){
    return err;
  }

  return Error.ok;
}

Exception
App_main(App_c* app, const Allocator_i* allocator)
{
  utracef("App_main app\n");

  io_c fstream;

  e$(io.fattach(&fstream, stdout, allocator));

  except_traceback(err, io.fprintf(&fstream, "hello world CEX\n"))
  {
    return err;
  }

  return Error.ok;
}

void
App_destroy(App_c* app, const Allocator_i* allocator)
{
  utracef("shutdown app\n");
}

const struct __class__App App = {
  // Autogenerated by CEX
  // clang-format off
    .create = App_create,
    .main = App_main,
    .destroy = App_destroy,
  // clang-format on
};
