#pragma once
#define CEX_BUILD

#if defined(CEX_BUILD)
#    include "cex.h"


typedef struct serdegen_field_s
{
    str_s type;
    char* name;
    char* json_name;
    struct
    {
        bool is_ptr;
        bool is_array;
        bool is_hashmap;
        bool is_optional;
        bool is_skipped;
    } flags;
} serdegen_field_s;

typedef struct serdegen_type_s
{
    char* name;
    arr$(serdegen_field_s*) fields;
    struct
    {
        bool is_struct;
    } flags;
} serdegen_type_s;

typedef struct CexSerdeGen_kw
{
    char* namespace;
    u32 buf_initial_capacity;
    char* workdir;
    char* outdir;
} CexSerdeGen_kw;

typedef struct CexSerdeGen_c
{
    IAllocator allc;
    hm$(str_s, serdegen_type_s*) types;
    arr$(char*) includes;
    char* namespace;
    sbuf_c c_file_content;
    sbuf_c h_file_content;
    char* workdir;
    char* outdir;
    char* target;
    char* c_out_name;
    char* h_out_name;
} CexSerdeGen_c;

struct __cex_namespace__CexSerdeGen
{
    // Autogenerated by CEX
    // clang-format off

    Exception       (*create)(CexSerdeGen_c* self, IAllocator allc, CexSerdeGen_kw* kwargs);
    Exception       (*generate_full)(CexSerdeGen_c* self);
    Exception       (*process_file)(CexSerdeGen_c* self, char* path);
    Exception       (*run)(CexSerdeGen_c* self);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__CexSerdeGen CexSerdeGen;

#endif
