#include "SerdeGen.h"


Exception
SerdeGen_create(SerdeGen_c* self, IAllocator allc)
{
    uassert(self);
    uassert(allc->meta.is_arena && "Expected arena allocator");

    *self = (SerdeGen_c){
        .allc = allc,
        .types = arr$new(self->types, allc),
    };

    return EOK;
}

Exception
SerdeGen_process_code(SerdeGen_c* self, char* code, usize code_len)
{
    uassert(self);

    if (!code) { return "code is NULL"; }
    if (code_len == 0) { code_len = str.len(code); }


    mem$arena(256 * 1024, _)
    {
        arr$(cex_token_s) items = arr$new(items, _);

        CexParser_c lx = CexParser.create(code, code_len, true);
        cex_token_s t;
        while ((t = CexParser.next_entity(&lx, &items)).type) {
            if (t.type == CexTkn__error) {
                return e$raise(
                    Error.integrity,
                    "Error parsing code, at line: %d, cursor: %d",
                    lx.line,
                    (i32)(lx.cur - lx.content)
                );
            }

            cex_decl_s* d = CexParser.decl_parse(&lx, t, items, NULL, _);
            if (d == NULL) { continue; }

            log$info("Got item: type=%s Name: %S\n", CexTkn_str[d->type], d->name);
        }
    }


    return EOK;
}

const struct __cex_namespace__SerdeGen SerdeGen = {
    // Autogenerated by CEX
    // clang-format off

    .create = SerdeGen_create,
    .process_code = SerdeGen_process_code,

    // clang-format on
};
