#pragma once
#include "cex.h"


typedef struct serdegen_type_s {

} serdegen_type_s;

typedef struct SerdeGen_c
{
    IAllocator allc;
    arr$(serdegen_type_s) types;
} SerdeGen_c;

struct __cex_namespace__SerdeGen {
    // Autogenerated by CEX
    // clang-format off

    Exception       (*create)(SerdeGen_c* self, IAllocator allc);
    Exception       (*process_code)(SerdeGen_c* self, char* code, usize code_len);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__SerdeGen SerdeGen;

