// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/sview.h>

// IMPORTANT: wrapping works only with gcc  `-Wl,--wrap=Shmem_new,--wrap=Protocol_event_emitter_new`  flag
FAKE_VALUE_FUNC(bool, __wrap_sview__isvalid, const str_c*)bool __real_sview__isvalid(const str_c*);

FAKE_VALUE_FUNC(ssize_t, __wrap_sview__index, str_c*, char)ssize_t __real_sview__index(str_c*, char);

FAKE_VALUE_FUNC(str_c, __wrap_sview_cstr, const char*)str_c __real_sview_cstr(const char*);

FAKE_VALUE_FUNC(str_c, __wrap_sview_cbuf, char*, size_t)str_c __real_sview_cbuf(char*, size_t);

FAKE_VALUE_FUNC(str_c, __wrap_sview_sub, str_c, ssize_t, ssize_t)str_c __real_sview_sub(str_c, ssize_t, ssize_t);

FAKE_VALUE_FUNC(Exc, __wrap_sview_copy, str_c, char*, size_t)Exception __real_sview_copy(str_c, char*, size_t);

FAKE_VALUE_FUNC(size_t, __wrap_sview_length, str_c)size_t __real_sview_length(str_c);

FAKE_VALUE_FUNC(bool, __wrap_sview_is_valid, str_c)bool __real_sview_is_valid(str_c);

FAKE_VALUE_FUNC(char*, __wrap_sview_iter, str_c, cex_iterator_s*)char* __real_sview_iter(str_c, cex_iterator_s*);

FAKE_VALUE_FUNC(ssize_t, __wrap_sview_indexof, str_c, str_c, size_t, size_t)ssize_t __real_sview_indexof(str_c, str_c, size_t, size_t);

FAKE_VALUE_FUNC(bool, __wrap_sview_contains, str_c, str_c)bool __real_sview_contains(str_c, str_c);

FAKE_VALUE_FUNC(bool, __wrap_sview_starts_with, str_c, str_c)bool __real_sview_starts_with(str_c, str_c);

FAKE_VALUE_FUNC(bool, __wrap_sview_ends_with, str_c, str_c)bool __real_sview_ends_with(str_c, str_c);

FAKE_VALUE_FUNC(str_c*, __wrap_sview_iter_split, str_c, const char, cex_iterator_s*)str_c* __real_sview_iter_split(str_c, const char, cex_iterator_s*);


const struct __module__sview sview = {
    // Autogenerated by CEX
    // clang-format off
    .cstr = sview_cstr,
    .cbuf = sview_cbuf,
    .sub = sview_sub,
    .copy = sview_copy,
    .length = sview_length,
    .is_valid = sview_is_valid,
    .iter = sview_iter,
    .indexof = sview_indexof,
    .contains = sview_contains,
    .starts_with = sview_starts_with,
    .ends_with = sview_ends_with,
    .iter_split = sview_iter_split,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__sview__wrap__resetall(void) {
    RESET_FAKE(__wrap_sview__isvalid)
    RESET_FAKE(__wrap_sview__index)
    RESET_FAKE(__wrap_sview_cstr)
    RESET_FAKE(__wrap_sview_cbuf)
    RESET_FAKE(__wrap_sview_sub)
    RESET_FAKE(__wrap_sview_copy)
    RESET_FAKE(__wrap_sview_length)
    RESET_FAKE(__wrap_sview_is_valid)
    RESET_FAKE(__wrap_sview_iter)
    RESET_FAKE(__wrap_sview_indexof)
    RESET_FAKE(__wrap_sview_contains)
    RESET_FAKE(__wrap_sview_starts_with)
    RESET_FAKE(__wrap_sview_ends_with)
    RESET_FAKE(__wrap_sview_iter_split)
}

