// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/list.h>

// IMPORTANT: wrapping works only with gcc  `-Wl,--wrap=Shmem_new,--wrap=Protocol_event_emitter_new`  flag
FAKE_VALUE_FUNC(list_head_s*, __wrap_list__head, list_c*)list_head_s* __real_list__head(list_c*);

FAKE_VALUE_FUNC(size_t, __wrap_list__alloc_capacity, size_t)size_t __real_list__alloc_capacity(size_t);

FAKE_VALUE_FUNC(void*, __wrap_list__elidx, list_head_s*, size_t)void* __real_list__elidx(list_head_s*, size_t);

FAKE_VALUE_FUNC(list_head_s*, __wrap_list__realloc, list_head_s*, size_t)list_head_s* __real_list__realloc(list_head_s*, size_t);

FAKE_VALUE_FUNC(size_t, __wrap_list__alloc_size, size_t, size_t, size_t)size_t __real_list__alloc_size(size_t, size_t, size_t);

FAKE_VALUE_FUNC(Exc, __wrap_list_create, list_c*, size_t, size_t, size_t, const Allocator_c*)Exception __real_list_create(list_c*, size_t, size_t, size_t, const Allocator_c*);

FAKE_VALUE_FUNC(Exc, __wrap_list_append, void*, void*)Exception __real_list_append(void*, void*);

FAKE_VALUE_FUNC(Exc, __wrap_list_extend, void*, void*, size_t)Exception __real_list_extend(void*, void*, size_t);

FAKE_VALUE_FUNC(size_t, __wrap_list_count, void*)size_t __real_list_count(void*);

FAKE_VALUE_FUNC(void*, __wrap_list_destroy, void*)void* __real_list_destroy(void*);

FAKE_VALUE_FUNC(void*, __wrap_list_iter, void*, cex_iterator_s*)void* __real_list_iter(void*, cex_iterator_s*);


const struct __module__list list = {
    // Autogenerated by CEX
    // clang-format off
    .create = list_create,
    .append = list_append,
    .extend = list_extend,
    .count = list_count,
    .destroy = list_destroy,
    .iter = list_iter,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__list__wrap__resetall(void) {
    RESET_FAKE(__wrap_list__head)
    RESET_FAKE(__wrap_list__alloc_capacity)
    RESET_FAKE(__wrap_list__elidx)
    RESET_FAKE(__wrap_list__realloc)
    RESET_FAKE(__wrap_list__alloc_size)
    RESET_FAKE(__wrap_list_create)
    RESET_FAKE(__wrap_list_append)
    RESET_FAKE(__wrap_list_extend)
    RESET_FAKE(__wrap_list_count)
    RESET_FAKE(__wrap_list_destroy)
    RESET_FAKE(__wrap_list_iter)
}

