// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <_cexlib/argparse.h>


FAKE_VOID_FUNC(argparse_usage, argparse_c*)
FAKE_VALUE_FUNC(Exc, argparse_parse, argparse_c*, int, char**)
FAKE_VALUE_FUNC(u32, argparse_argc, argparse_c*)
FAKE_VALUE_FUNC(char**, argparse_argv, argparse_c*)

const struct __module__argparse argparse = {
    // Autogenerated by CEX
    // clang-format off
    .usage = argparse_usage,
    .parse = argparse_parse,
    .argc = argparse_argc,
    .argv = argparse_argv,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__argparse__resetall(void) {
    RESET_FAKE(argparse_usage)
    RESET_FAKE(argparse_parse)
    RESET_FAKE(argparse_argc)
    RESET_FAKE(argparse_argv)
}

