// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/dlist.h>


FAKE_VALUE_FUNC(dlist_head_s*, _dlist__head, dlist_c*)
FAKE_VALUE_FUNC(size_t, _dlist__alloc_capacity, size_t)
FAKE_VALUE_FUNC(void*, _dlist__elidx, dlist_head_s*, size_t)
FAKE_VALUE_FUNC(dlist_head_s*, _dlist__realloc, dlist_head_s*, size_t)
FAKE_VALUE_FUNC(size_t, _dlist__alloc_size, size_t, size_t, size_t)
FAKE_VALUE_FUNC(Exc, _dlist_create, dlist_c*, size_t, size_t, size_t, const Allocator_c*)
FAKE_VALUE_FUNC(Exc, _dlist_append, void*, void*)
FAKE_VALUE_FUNC(Exc, _dlist_extend, void*, void*, size_t)
FAKE_VALUE_FUNC(size_t, _dlist_count, void*)
FAKE_VALUE_FUNC(void*, _dlist_destroy, void*)
FAKE_VALUE_FUNC(void*, _dlist_iter, void*, cex_iterator_s*)

const struct __module__dlist dlist = {
    // Autogenerated by CEX
    // clang-format off
    .create = _dlist_create,
    .append = _dlist_append,
    .extend = _dlist_extend,
    .count = _dlist_count,
    .destroy = _dlist_destroy,
    .iter = _dlist_iter,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__dlist__resetall(void) {
    RESET_FAKE(_dlist__head)
    RESET_FAKE(_dlist__alloc_capacity)
    RESET_FAKE(_dlist__elidx)
    RESET_FAKE(_dlist__realloc)
    RESET_FAKE(_dlist__alloc_size)
    RESET_FAKE(_dlist_create)
    RESET_FAKE(_dlist_append)
    RESET_FAKE(_dlist_extend)
    RESET_FAKE(_dlist_count)
    RESET_FAKE(_dlist_destroy)
    RESET_FAKE(_dlist_iter)
}

