// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/argparse.h>


FAKE_VALUE_FUNC(const char*, prefix_skip, const char*, const char*)
FAKE_VALUE_FUNC(int, prefix_cmp, const char*, const char*)
FAKE_VOID_FUNC(argparse_usage, argparse_c*)
FAKE_VALUE_FUNC(Exc, argparse_parse, argparse_c*, int, char**)

const struct __module__argparse argparse = {
    // Autogenerated by CEX
    // clang-format off
    .usage = argparse_usage,
    .parse = argparse_parse,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__argparse__resetall(void) {
    RESET_FAKE(prefix_skip)
    RESET_FAKE(prefix_cmp)
    RESET_FAKE(argparse_usage)
    RESET_FAKE(argparse_parse)
}

