// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/io.h>

// IMPORTANT: wrapping works only with gcc  `-Wl,--wrap=Shmem_new,--wrap=Protocol_event_emitter_new`  flag
FAKE_VALUE_FUNC(Exc, __wrap_io_fopen, io_c*, const char*, const char*, const Allocator_c*)Exception __real_io_fopen(io_c*, const char*, const char*, const Allocator_c*);

FAKE_VALUE_FUNC(Exc, __wrap_io_fattach, io_c*, FILE*, const Allocator_c*)Exception __real_io_fattach(io_c*, FILE*, const Allocator_c*);

FAKE_VALUE_FUNC(size_t, __wrap_io_size, io_c*)size_t __real_io_size(io_c*);

FAKE_VALUE_FUNC(Exc, __wrap_io_readall, io_c*, sview_c*)Exception __real_io_readall(io_c*, sview_c*);

FAKE_VOID_FUNC(__wrap_io_close, io_c*)void __real_io_close(io_c*);


const struct __module__io io = {
    // Autogenerated by CEX
    // clang-format off
    .fopen = io_fopen,
    .fattach = io_fattach,
    .size = io_size,
    .readall = io_readall,
    .close = io_close,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__io__wrap__resetall(void) {
    RESET_FAKE(__wrap_io_fopen)
    RESET_FAKE(__wrap_io_fattach)
    RESET_FAKE(__wrap_io_size)
    RESET_FAKE(__wrap_io_readall)
    RESET_FAKE(__wrap_io_close)
}

