// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/argparse.h>

// IMPORTANT: wrapping works only with gcc  `-Wl,--wrap=Shmem_new,--wrap=Protocol_event_emitter_new`  flag
FAKE_VALUE_FUNC(const char*, __wrap_prefix_skip, const char*, const char*)const char* __real_prefix_skip(const char*, const char*);

FAKE_VALUE_FUNC(int, __wrap_prefix_cmp, const char*, const char*)int __real_prefix_cmp(const char*, const char*);

FAKE_VOID_FUNC(__wrap_argparse_usage, argparse_c*)void __real_argparse_usage(argparse_c*);

FAKE_VALUE_FUNC(Exc, __wrap_argparse_parse, argparse_c*, int, char**)Exception __real_argparse_parse(argparse_c*, int, char**);


const struct __module__argparse argparse = {
    // Autogenerated by CEX
    // clang-format off
    .usage = argparse_usage,
    .parse = argparse_parse,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__argparse__wrap__resetall(void) {
    RESET_FAKE(__wrap_prefix_skip)
    RESET_FAKE(__wrap_prefix_cmp)
    RESET_FAKE(__wrap_argparse_usage)
    RESET_FAKE(__wrap_argparse_parse)
}

