// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <_cexcore/list.h>


FAKE_VALUE_FUNC(Exc, list_create, list_c*, size_t, size_t, size_t, const Allocator_i*)
FAKE_VALUE_FUNC(Exc, list_create_static, list_c*, void*, size_t, size_t, size_t)
FAKE_VALUE_FUNC(Exc, list_insert, void*, void*, size_t)
FAKE_VALUE_FUNC(Exc, list_del, void*, size_t)
FAKE_VOID_FUNC(list_sort, void*, int (*comp)(const, const)
FAKE_VALUE_FUNC(Exc, list_append, void*, void*)
FAKE_VOID_FUNC(list_clear, void*)
FAKE_VALUE_FUNC(Exc, list_extend, void*, void*, size_t)
FAKE_VALUE_FUNC(size_t, list_len, void*)
FAKE_VALUE_FUNC(size_t, list_capacity, void*)
FAKE_VALUE_FUNC(void*, list_destroy, void*)
FAKE_VALUE_FUNC(void*, list_iter, void*, cex_iterator_s*)

const struct __module__list list = {
    // Autogenerated by CEX
    // clang-format off
    .create = list_create,
    .create_static = list_create_static,
    .insert = list_insert,
    .del = list_del,
    .sort = list_sort,
    .append = list_append,
    .clear = list_clear,
    .extend = list_extend,
    .len = list_len,
    .capacity = list_capacity,
    .destroy = list_destroy,
    .iter = list_iter,
    // clang-format on
};
// clang-format off


static void fake__cex__cexcore__list__resetall(void) {
    RESET_FAKE(list_create)
    RESET_FAKE(list_create_static)
    RESET_FAKE(list_insert)
    RESET_FAKE(list_del)
    RESET_FAKE(list_sort)
    RESET_FAKE(list_append)
    RESET_FAKE(list_clear)
    RESET_FAKE(list_extend)
    RESET_FAKE(list_len)
    RESET_FAKE(list_capacity)
    RESET_FAKE(list_destroy)
    RESET_FAKE(list_iter)
}

