// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/sview.h>


FAKE_VALUE_FUNC(bool, sview__isvalid, const sview_c*)
FAKE_VALUE_FUNC(ssize_t, sview__index, sview_c*, const char*, u8)
FAKE_VALUE_FUNC(sview_c, sview_cstr, const char*)
FAKE_VALUE_FUNC(sview_c, sview_cbuf, char*, size_t)
FAKE_VALUE_FUNC(sview_c, sview_sub, sview_c, ssize_t, ssize_t)
FAKE_VALUE_FUNC(Exc, sview_copy, sview_c, char*, size_t)
FAKE_VALUE_FUNC(size_t, sview_len, sview_c)
FAKE_VALUE_FUNC(bool, sview_is_valid, sview_c)
FAKE_VALUE_FUNC(char*, sview_iter, sview_c, cex_iterator_s*)
FAKE_VALUE_FUNC(ssize_t, sview_indexof, sview_c, sview_c, size_t, size_t)
FAKE_VALUE_FUNC(bool, sview_contains, sview_c, sview_c)
FAKE_VALUE_FUNC(bool, sview_starts_with, sview_c, sview_c)
FAKE_VALUE_FUNC(bool, sview_ends_with, sview_c, sview_c)
FAKE_VOID_FUNC(sview__strip_left, sview_c*)
FAKE_VOID_FUNC(sview__strip_right, sview_c*)
FAKE_VALUE_FUNC(sview_c, sview_lstrip, sview_c)
FAKE_VALUE_FUNC(sview_c, sview_rstrip, sview_c)
FAKE_VALUE_FUNC(sview_c, sview_strip, sview_c)
FAKE_VALUE_FUNC(int, sview_cmp, sview_c, sview_c)
FAKE_VALUE_FUNC(int, sview_cmpc, sview_c, const char*)
FAKE_VALUE_FUNC(sview_c*, sview_iter_split, sview_c, const char*, cex_iterator_s*)

const struct __module__sview sview = {
    // Autogenerated by CEX
    // clang-format off
    .cstr = sview_cstr,
    .cbuf = sview_cbuf,
    .sub = sview_sub,
    .copy = sview_copy,
    .len = sview_len,
    .is_valid = sview_is_valid,
    .iter = sview_iter,
    .indexof = sview_indexof,
    .contains = sview_contains,
    .starts_with = sview_starts_with,
    .ends_with = sview_ends_with,
    .lstrip = sview_lstrip,
    .rstrip = sview_rstrip,
    .strip = sview_strip,
    .cmp = sview_cmp,
    .cmpc = sview_cmpc,
    .iter_split = sview_iter_split,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__sview__resetall(void) {
    RESET_FAKE(sview__isvalid)
    RESET_FAKE(sview__index)
    RESET_FAKE(sview_cstr)
    RESET_FAKE(sview_cbuf)
    RESET_FAKE(sview_sub)
    RESET_FAKE(sview_copy)
    RESET_FAKE(sview_len)
    RESET_FAKE(sview_is_valid)
    RESET_FAKE(sview_iter)
    RESET_FAKE(sview_indexof)
    RESET_FAKE(sview_contains)
    RESET_FAKE(sview_starts_with)
    RESET_FAKE(sview_ends_with)
    RESET_FAKE(sview__strip_left)
    RESET_FAKE(sview__strip_right)
    RESET_FAKE(sview_lstrip)
    RESET_FAKE(sview_rstrip)
    RESET_FAKE(sview_strip)
    RESET_FAKE(sview_cmp)
    RESET_FAKE(sview_cmpc)
    RESET_FAKE(sview_iter_split)
}

