// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/deque.h>

// IMPORTANT: wrapping works only with gcc  `-Wl,--wrap=Shmem_new,--wrap=Protocol_event_emitter_new`  flag
FAKE_VALUE_FUNC(deque_head_s*, __wrap__deque__head, deque_c)deque_head_s* __real__deque__head(deque_c);

FAKE_VALUE_FUNC(size_t, __wrap__deque__alloc_capacity, size_t)size_t __real__deque__alloc_capacity(size_t);

FAKE_VALUE_FUNC(void*, __wrap__deque__get_byindex, deque_head_s*, size_t)void* __real__deque__get_byindex(deque_head_s*, size_t);

FAKE_VALUE_FUNC(size_t, __wrap__deque__alloc_size, size_t, size_t, size_t)size_t __real__deque__alloc_size(size_t, size_t, size_t);

FAKE_VALUE_FUNC(Exc, __wrap__deque_validate, deque_c)Exception __real__deque_validate(deque_c);

FAKE_VALUE_FUNC(Exc, __wrap__deque_create, deque_c*, size_t, bool, size_t, size_t, const Allocator_c*)Exception __real__deque_create(deque_c*, size_t, bool, size_t, size_t, const Allocator_c*);

FAKE_VALUE_FUNC(Exc, __wrap__deque_create_static, deque_c*, void*, size_t, bool, size_t, size_t)Exception __real__deque_create_static(deque_c*, void*, size_t, bool, size_t, size_t);

FAKE_VALUE_FUNC(Exc, __wrap__deque_append, deque_c*, const void*)Exception __real__deque_append(deque_c*, const void*);

FAKE_VALUE_FUNC(Exc, __wrap__deque_enqueue, deque_c*, const void*)Exception __real__deque_enqueue(deque_c*, const void*);

FAKE_VALUE_FUNC(Exc, __wrap__deque_push, deque_c*, const void*)Exception __real__deque_push(deque_c*, const void*);

FAKE_VALUE_FUNC(void*, __wrap__deque_dequeue, deque_c*)void* __real__deque_dequeue(deque_c*);

FAKE_VALUE_FUNC(void*, __wrap__deque_pop, deque_c*)void* __real__deque_pop(deque_c*);

FAKE_VALUE_FUNC(void*, __wrap__deque_get, deque_c*, size_t)void* __real__deque_get(deque_c*, size_t);

FAKE_VALUE_FUNC(size_t, __wrap__deque_count, const deque_c*)size_t __real__deque_count(const deque_c*);

FAKE_VOID_FUNC(__wrap__deque_clear, deque_c*)void __real__deque_clear(deque_c*);

FAKE_VALUE_FUNC(void*, __wrap__deque_destroy, deque_c*)void* __real__deque_destroy(deque_c*);

FAKE_VALUE_FUNC(void*, __wrap__deque_iter_get, deque_c*, i32, cex_iterator_s*)void* __real__deque_iter_get(deque_c*, i32, cex_iterator_s*);

FAKE_VALUE_FUNC(void*, __wrap__deque_iter_fetch, deque_c*, i32, cex_iterator_s*)void* __real__deque_iter_fetch(deque_c*, i32, cex_iterator_s*);


const struct __module__deque deque = {
    // Autogenerated by CEX
    // clang-format off
    .validate = _deque_validate,
    .create = _deque_create,
    .create_static = _deque_create_static,
    .append = _deque_append,
    .enqueue = _deque_enqueue,
    .push = _deque_push,
    .dequeue = _deque_dequeue,
    .pop = _deque_pop,
    .get = _deque_get,
    .count = _deque_count,
    .clear = _deque_clear,
    .destroy = _deque_destroy,
    .iter_get = _deque_iter_get,
    .iter_fetch = _deque_iter_fetch,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__deque__wrap__resetall(void) {
    RESET_FAKE(__wrap__deque__head)
    RESET_FAKE(__wrap__deque__alloc_capacity)
    RESET_FAKE(__wrap__deque__get_byindex)
    RESET_FAKE(__wrap__deque__alloc_size)
    RESET_FAKE(__wrap__deque_validate)
    RESET_FAKE(__wrap__deque_create)
    RESET_FAKE(__wrap__deque_create_static)
    RESET_FAKE(__wrap__deque_append)
    RESET_FAKE(__wrap__deque_enqueue)
    RESET_FAKE(__wrap__deque_push)
    RESET_FAKE(__wrap__deque_dequeue)
    RESET_FAKE(__wrap__deque_pop)
    RESET_FAKE(__wrap__deque_get)
    RESET_FAKE(__wrap__deque_count)
    RESET_FAKE(__wrap__deque_clear)
    RESET_FAKE(__wrap__deque_destroy)
    RESET_FAKE(__wrap__deque_iter_get)
    RESET_FAKE(__wrap__deque_iter_fetch)
}

