// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/dlist.h>

// IMPORTANT: wrapping works only with gcc  `-Wl,--wrap=Shmem_new,--wrap=Protocol_event_emitter_new`  flag
FAKE_VALUE_FUNC(dlist_head_s*, __wrap__dlist__head, dlist_c*)dlist_head_s* __real__dlist__head(dlist_c*);

FAKE_VALUE_FUNC(size_t, __wrap__dlist__alloc_capacity, size_t)size_t __real__dlist__alloc_capacity(size_t);

FAKE_VALUE_FUNC(void*, __wrap__dlist__elidx, dlist_head_s*, size_t)void* __real__dlist__elidx(dlist_head_s*, size_t);

FAKE_VALUE_FUNC(dlist_head_s*, __wrap__dlist__realloc, dlist_head_s*, size_t)dlist_head_s* __real__dlist__realloc(dlist_head_s*, size_t);

FAKE_VALUE_FUNC(size_t, __wrap__dlist__alloc_size, size_t, size_t, size_t)size_t __real__dlist__alloc_size(size_t, size_t, size_t);

FAKE_VALUE_FUNC(Exc, __wrap__dlist_create, dlist_c*, size_t, size_t, size_t, const Allocator_c*)Exception __real__dlist_create(dlist_c*, size_t, size_t, size_t, const Allocator_c*);

FAKE_VALUE_FUNC(Exc, __wrap__dlist_append, void*, void*)Exception __real__dlist_append(void*, void*);

FAKE_VALUE_FUNC(Exc, __wrap__dlist_extend, void*, void*, size_t)Exception __real__dlist_extend(void*, void*, size_t);

FAKE_VALUE_FUNC(size_t, __wrap__dlist_count, void*)size_t __real__dlist_count(void*);

FAKE_VALUE_FUNC(void*, __wrap__dlist_destroy, void*)void* __real__dlist_destroy(void*);

FAKE_VALUE_FUNC(void*, __wrap__dlist_iter, void*, cex_iterator_s*)void* __real__dlist_iter(void*, cex_iterator_s*);


const struct __module__dlist dlist = {
    // Autogenerated by CEX
    // clang-format off
    .create = _dlist_create,
    .append = _dlist_append,
    .extend = _dlist_extend,
    .count = _dlist_count,
    .destroy = _dlist_destroy,
    .iter = _dlist_iter,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__dlist__wrap__resetall(void) {
    RESET_FAKE(__wrap__dlist__head)
    RESET_FAKE(__wrap__dlist__alloc_capacity)
    RESET_FAKE(__wrap__dlist__elidx)
    RESET_FAKE(__wrap__dlist__realloc)
    RESET_FAKE(__wrap__dlist__alloc_size)
    RESET_FAKE(__wrap__dlist_create)
    RESET_FAKE(__wrap__dlist_append)
    RESET_FAKE(__wrap__dlist_extend)
    RESET_FAKE(__wrap__dlist_count)
    RESET_FAKE(__wrap__dlist_destroy)
    RESET_FAKE(__wrap__dlist_iter)
}

