// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// clang-format off
#include <cex/cextest/fff.h>
#include <cex/cexlib/sbuf.h>

// IMPORTANT: wrapping works only with gcc  `-Wl,--wrap=Shmem_new,--wrap=Protocol_event_emitter_new`  flag
FAKE_VALUE_FUNC(sbuf_head_s*, __wrap__sbuf__head, sbuf_c)sbuf_head_s* __real__sbuf__head(sbuf_c);

FAKE_VALUE_FUNC(size_t, __wrap__sbuf__alloc_capacity, size_t)size_t __real__sbuf__alloc_capacity(size_t);

FAKE_VALUE_FUNC(Exc, __wrap__sbuf__grow_buffer, sbuf_c*, u32)Exception __real__sbuf__grow_buffer(sbuf_c*, u32);

FAKE_VALUE_FUNC(Exc, __wrap__sbuf_create, sbuf_c*, u32, const Allocator_c*)Exception __real__sbuf_create(sbuf_c*, u32, const Allocator_c*);

FAKE_VALUE_FUNC(Exc, __wrap__sbuf_create_static, sbuf_c*, char*, size_t)Exception __real__sbuf_create_static(sbuf_c*, char*, size_t);

FAKE_VALUE_FUNC(Exc, __wrap__sbuf_grow, sbuf_c*, u32)Exception __real__sbuf_grow(sbuf_c*, u32);

FAKE_VALUE_FUNC(Exc, __wrap__sbuf_append_c, sbuf_c*, char*)Exception __real__sbuf_append_c(sbuf_c*, char*);

FAKE_VALUE_FUNC(Exc, __wrap__sbuf_replace, sbuf_c*, const str_c, const str_c)Exception __real__sbuf_replace(sbuf_c*, const str_c, const str_c);

FAKE_VALUE_FUNC(Exc, __wrap__sbuf_append, sbuf_c*, str_c)Exception __real__sbuf_append(sbuf_c*, str_c);

FAKE_VOID_FUNC(__wrap__sbuf_clear, sbuf_c*)void __real__sbuf_clear(sbuf_c*);

FAKE_VALUE_FUNC(u32, __wrap__sbuf_length, const sbuf_c)u32 __real__sbuf_length(const sbuf_c);

FAKE_VALUE_FUNC(u32, __wrap__sbuf_capacity, const sbuf_c)u32 __real__sbuf_capacity(const sbuf_c);

FAKE_VALUE_FUNC(sbuf_c, __wrap__sbuf_destroy, sbuf_c*)sbuf_c __real__sbuf_destroy(sbuf_c*);


const struct __module__sbuf sbuf = {
    // Autogenerated by CEX
    // clang-format off
    .create = _sbuf_create,
    .create_static = _sbuf_create_static,
    .grow = _sbuf_grow,
    .append_c = _sbuf_append_c,
    .replace = _sbuf_replace,
    .append = _sbuf_append,
    .clear = _sbuf_clear,
    .length = _sbuf_length,
    .capacity = _sbuf_capacity,
    .destroy = _sbuf_destroy,
    // clang-format on
};
// clang-format off


static void fake__cex__cexlib__sbuf__wrap__resetall(void) {
    RESET_FAKE(__wrap__sbuf__head)
    RESET_FAKE(__wrap__sbuf__alloc_capacity)
    RESET_FAKE(__wrap__sbuf__grow_buffer)
    RESET_FAKE(__wrap__sbuf_create)
    RESET_FAKE(__wrap__sbuf_create_static)
    RESET_FAKE(__wrap__sbuf_grow)
    RESET_FAKE(__wrap__sbuf_append_c)
    RESET_FAKE(__wrap__sbuf_replace)
    RESET_FAKE(__wrap__sbuf_append)
    RESET_FAKE(__wrap__sbuf_clear)
    RESET_FAKE(__wrap__sbuf_length)
    RESET_FAKE(__wrap__sbuf_capacity)
    RESET_FAKE(__wrap__sbuf_destroy)
}

