#pragma once
#include "all.h"

#if !defined(cex$enable_minimal) || defined(cex$enable_mem)

/// Maximum nesting depth for mem$scope() calls
#    define CEX_ALLOCATOR_MAX_SCOPE_STACK 16

typedef struct allocator_arena_page_s allocator_arena_page_s;

/// Keyword arguments for AllocatorArena.create() — page_size and behavior flags
typedef struct
{
    usize page_size;     ///< Arena page size (default: CEX_ALLOCATOR_TEMP_PAGE_SIZE = 256KB)
    bool disable_scopes; ///< If true, arena works without mem$scope() (manual destroy only)
} AllocatorArena_kw;

/// Arena allocator instance: vtable pointer, page list, scope stack, and allocation stats
typedef struct
{
    alignas(64) const Allocator_i alloc;

    allocator_arena_page_s* last_page;
    usize used;

    usize page_size;
    u32 scope_depth;     // current scope mark, used by mem$scope
    bool disable_scopes; // if true, scope_enter/scope_exit are no-ops, destroy releases all
    struct
    {
        usize bytes_alloc;
        usize bytes_realloc;
        usize bytes_free;
        u32 pages_created;
        u32 pages_free;
    } stats;

    // each mark is a `used` value at alloc.scope_enter()
    usize scope_stack[CEX_ALLOCATOR_MAX_SCOPE_STACK];

} AllocatorArena_c;

static_assert(sizeof(AllocatorArena_c) <= 256, "size!");
static_assert(offsetof(AllocatorArena_c, alloc) == 0, "base must be the 1st struct member");

/// A single arena memory page: prev-page link, cursor, capacity, poison barrier, trailing data
typedef struct allocator_arena_page_s
{
    alignas(64) allocator_arena_page_s* prev_page;
    usize used_start; // as of AllocatorArena.used field
    u32 cursor;       // current allocated size of this page
    u32 capacity;     // max capacity of this page (excluding header)
    void* last_alloc; // last allocated pointer (viable for realloc)
    u8 __poison_area[(sizeof(usize) == 8 ? 32 : 44)]; // barrier of sanitizer poison + space reserve
    char data[];                                      // trailing chunk of data
} allocator_arena_page_s;
static_assert(sizeof(allocator_arena_page_s) == 64, "size!");
static_assert(alignof(allocator_arena_page_s) == 64, "align");
static_assert(offsetof(allocator_arena_page_s, data) == 64, "data must be aligned to 64");

/// Allocation record header stored before each allocated block (size, alignment, padding, free flag)
typedef struct allocator_arena_rec_s
{
    u32 size;         // allocation size
    u8 ptr_padding;   // padding in bytes to next rec (also poisoned!)
    u8 ptr_alignment; // requested pointer alignment
    u8 is_free;       // indication that address has been free()'d
    u8 ptr_offset;    // byte offset for allocated pointer for this item
} allocator_arena_rec_s;
static_assert(sizeof(allocator_arena_rec_s) == 8, "size!");
static_assert(offsetof(allocator_arena_rec_s, ptr_offset) == 7, "ptr_offset must be last");

extern
#    if !cex$is_freestanding
    _Thread_local
#    endif
    AllocatorArena_c _cex__default_global__allocator_temp;

/**
Namespace wrapping AllocatorArena operations: create, destroy, and sanitize.
*/
struct __cex_namespace__AllocatorArena {
    // Autogenerated by CEX
    // clang-format off

    /// Creates a new arena allocator with keyword args (AllocatorArena_kw), returns an IAllocator
    IAllocator      (*create)(const AllocatorArena_kw* kwargs);
    /// Destroys arena allocator and frees all allocated pages
    void            (*destroy)(IAllocator self);
    /// Validates arena allocator internal state: record headers, poison markers, and page integrity
    bool            (*sanitize)(IAllocator allc);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__AllocatorArena AllocatorArena;

#endif
