#pragma once
#if !defined(cex$enable_minimal) || defined(cex$enable_io)

#if defined(cex$enable_minimal) && !defined(cex$enable_mem)
#error "CEX io namespace depends on `#define cex$enable_mem`"
#endif

#include "all.h"

/// Makes string literal with ansi colored text
#define io$ansi(text, ansi_col) "\033[" ansi_col "m" text "\033[0m"

/**

## Input/Output

Cross-platform IO namespace.

### File load/save (easy api)

```c
e$ret(io.file.save("tests/data/text_file_write.txt", "Hello from CEX!\n"));

char* content = io.file.load("tests/data/text_file_write.txt", mem$); // NULL on error
io.printf("%s", content); // Hello from CEX!
mem$free(mem$, content);
```

### Low-level file api

- Read all content

```c
FILE* file;
e$ret(io.fopen(&file, "tests/data/text_file_50b.txt", "r"));

usize size = io.file.size(file); // 50

str_s content;
e$ret(io.fread_all(file, &content, mem$)); // content.buf is allocated by mem$
mem$free(mem$, content.buf);

io.fclose(&file); // file is set to NULL
```

- Read/write lines

```c
FILE* file;
e$ret(io.fopen(&file, "tests/data/text_file_write.txt", "w+"));

mem$scope(tmem$, _)
{
    // Write line by line
    e$ret(io.file.writeln(file, "hello"));
    e$ret(io.file.writeln(file, "world"));

    // Read line by line
    io.rewind(file);
    io.printf("%s\n", io.file.readln(file, _)); // hello (backed by temp allocator)

    // low-level api (uses heap allocator, needs free)
    str_s content;
    e$ret(io.fread_line(file, &content, mem$));
    io.printf("%S\n", content); // world
    mem$free(mem$, content.buf);
}
io.fclose(&file);
```

- Read/write bytes

```c
// Read bytes in a loop
FILE* file;
e$ret(io.fopen(&file, "tests/data/text_file_50b.txt", "r"));

char buf[128] = {0};
isize nread = 0;
while ((nread = io.fread(file, buf, 10))) {
    if (nread < 0) {
        // io.fread() error, os.get_last_error() gives the Exception
        break;
    }
    buf[10] = '\0';
    io.printf("%s", buf);
}
io.fclose(&file);

// Write bytes
e$ret(io.fopen(&file, "tests/data/text_file_write.txt", "w+"));
char data[] = "foobar";
e$ret(io.fwrite(file, data, arr$len(data)));
io.fclose(&file);
```

*/
struct __cex_namespace__io {
    // Autogenerated by CEX
    // clang-format off

    /// Closes file and set it to NULL.
    void            (*fclose)(FILE** file);
    /// Flush changes to file
    Exception       (*fflush)(FILE* file);
    /// Opens new file: io.fopen(&file, "file.txt", "r+")
    Exception       (*fopen)(FILE** file, char* filename, char* mode);
    /// Prints formatted string to the file. Uses CEX printf() engine with special formatting.
    Exc             (*fprintf)(FILE* stream, char* format,...);
    /// Read file contents into the buf, return nbytes read (can be < buff_len), 0 on EOF, negative on
    /// error (you may use os.get_last_error() for getting Exception for error, cross-platform )
    isize           (*fread)(FILE* file, void* buff, usize buff_len);
    /// Read all contents of the file, using allocator. You should free `s.buf` after.
    Exception       (*fread_all)(FILE* file, str_s* s, IAllocator allc);
    /// Reads line from a file into str_s buffer, allocates memory. You should free `s.buf` after.
    Exception       (*fread_line)(FILE* file, str_s* s, IAllocator allc);
    /// Seek file position
    Exception       (*fseek)(FILE* file, long offset, int whence);
    /// Returns current cursor position into `size` pointer
    Exception       (*ftell)(FILE* file, usize* size);
    /// Writes bytes to the file
    Exception       (*fwrite)(FILE* file, void* buff, usize buff_len);
    /// Check if current file supports ANSI colors and in interactive terminal mode
    bool            (*isatty)(FILE* file);
    /// Prints formatted string to stdout. Uses CEX printf() engine with special formatting.
    int             (*printf)(char* format,...);
    /// Rewind file cursor at the beginning
    void            (*rewind)(FILE* file);

    struct {
        /// Load full contents of the file at `path`, using text mode. Returns NULL on error.
        char*           (*load)(char* path, IAllocator allc);
        /// Reads line from file, allocates result. Returns NULL on error.
        char*           (*readln)(FILE* file, IAllocator allc);
        /// Saves full `contents` in the file at `path`, using text mode.
        Exception       (*save)(char* path, char* contents);
        /// Return full file size, always 0 for NULL file or atty
        usize           (*size)(FILE* file);
        /// Writes new line to the file
        Exception       (*writeln)(FILE* file, char* line);
    } file;

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__io io;

#endif
