#pragma once

#if !defined(cex$enable_minimal) || defined(cex$enable_str)
#include "cex_base.h"
#include <assert.h>

/// Dynamic string builder type (alias for char*, always null-terminated)
typedef char* sbuf_c;

/// Internal metadata header stored before the string buffer; the first byte (nullterm) is always 0
typedef struct
{
    alignas(alignof(u64)) struct
    {
        u8 nullterm; // always zero to prevent usage of direct buffer
        u8 elsize;   // maybe multibyte strings in the future?
        u32 magic;   // used for sanity checks
    } header;
    Exc err;
    const Allocator_i* allocator;
    usize capacity;
    usize length;
} sbuf_head_s;

static_assert(alignof(sbuf_head_s) == alignof(u64), "align");

/**

## String builder

Dynamic string builder class

Key features:

- Dynamically grown strings
- Supports CEX specific formats
- Can be backed by allocator or static buffer
- Error resilient - allows self as NULL
- `sbuf_c` - is an alias of `char*`, always null terminated, compatible with any C strings

- Allocator driven dynamic string
```c
sbuf_c s = sbuf.create(20, mem$);

// These may fail (you may use them with e$* checks or add final check)
sbuf.appendf(&s, "%s, CEX slice: %S\n", "456", str$s("slice"));
sbuf.append(&s, "some string");

e$except(err, sbuf.validate(&s)) {
    // Error handling
}

if (!sbuf.isvalid(&s)) {
    // Error, just a boolean flag
}

// Some other stuff
s[i]   // getting i-th character of string
strlen(s); // C strings work, because sbuf_c is vanilla char*
sbuf.len(&s); // faster way of getting length (uses metadata)
sbuf.set_len(&s, new_length); // set length (reallocates if it exceeds capacity)
sbuf.capacity(&s); // current capacity, 0 if error occurred
sbuf.clear(&s); // reset dynamic string + null term




// Frees the memory and sets s to NULL
sbuf.destroy(&s);
```

- Static buffer backed string
```c

// `buf` may be unaligned: the header is placed at the first aligned address.
// NOTE: `s` address is different, because `buf` will contain header and metadata, use only `s`
char buf[64];
sbuf_c s = sbuf.create_static(buf, arr$len(buf));

// You may check every operation if needed, but this more verbose
e$ret(sbuf.appendf(&s, "%s, CEX slice: %S\n", "456", str$s("slice")));
e$ret(sbuf.append(&s, "some string"));

// It's not mandatory, but will clean up buffer data at the end
sbuf.destroy(&s);
```

- `buf` may have any alignment; the header goes to the first `alignof(sbuf_head_s)`-aligned address, so `capacity = buf_size - alignment_slack - sizeof(sbuf_head_s) - 1`
- `buf_size` must be greater than `alignment_slack + sizeof(sbuf_head_s) + 1`, otherwise `create_static()` returns NULL
- Reserve room: the header is `sizeof(sbuf_head_s)` (40 bytes on 64-bit), plus up to `alignof(sbuf_head_s) - 1` bytes of alignment slack, plus the null terminator — up to 48 extra bytes on 64-bit
- `buf[0]` is always `\0`, so the raw buffer reads as an empty string even while `s` holds data
- Static builders cannot grow: appending past capacity sets `Error.overflow` and resets capacity to 0
- `destroy()` invalidates the header and null-terminates the data; a dynamic buffer is freed, a static buffer is not

*/
struct __cex_namespace__sbuf {
    // Autogenerated by CEX
    // clang-format off

    /// Append string to the builder
    Exc             (*append)(sbuf_c* self, char* s);
    /// Append format (using CEX formatting engine)
    Exc             (*appendf)(sbuf_c* self, char* format,...);
    /// Append format va (using CEX formatting engine), always null-terminating
    Exc             (*appendfva)(sbuf_c* self, char* format, va_list va);
    /// Returns string capacity from its metadata
    usize           (*capacity)(sbuf_c* self);
    /// Clears string
    void            (*clear)(sbuf_c* self);
    /// Creates new dynamic string builder backed by allocator
    sbuf_c          (*create)(usize capacity, IAllocator allocator);
    /// Creates string builder backed by a static buffer (aligned up; reserve up to 48 extra bytes for the header, alignment slack and null terminator)
    sbuf_c          (*create_static)(char* buf, usize buf_size);
    /// Destroys the string: frees the dynamic buffer, or invalidates the static buffer without freeing it; tolerates NULL self
    sbuf_c          (*destroy)(sbuf_c* self);
    /// Returns false if string invalid
    bool            (*isvalid)(sbuf_c* self);
    /// Returns string length from its metadata
    usize           (*len)(sbuf_c* self);
    /// Sets the length of a string to any value, if new_length greater than capacity, re-allocates more
    /// space, always null-terminating. Newly allocated space is not ZII'ed, you must fill it yourself.
    Exc             (*set_len)(sbuf_c* self, usize new_length);
    /// Validate dynamic string state, with detailed Exception
    Exception       (*validate)(sbuf_c* self);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__sbuf sbuf;

#endif
