// Autogenerated serde engine by CEX
// DO NOT EDIT
//
#include "cex.h"
#include "cexstd/json/json.h"
#include "tests/cexstd/serde//basic/Stock.h"
#include "tests/cexstd/serde//basic/Position.h"

struct __cex_namespace__serdegen {
    // Autogenerated by CEX
    // clang-format off


    struct {
        Exception       (*deserialize)(json_rd_c* jr, Position* out_item, IAllocator allc);
        void            (*destroy)(Position* item, IAllocator allc);
        Exc             (*print)(Position* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Position* item);
    } Position;

    struct {
        Exception       (*deserialize)(json_rd_c* jr, Stock* out_item, IAllocator allc);
        void            (*destroy)(Stock* item, IAllocator allc);
        Exc             (*print)(Stock* item, json_wr_kw* json_writer_kwargs);
        Exception       (*serialize)(json_wr_c* jw, Stock* item);
    } Stock;

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__serdegen serdegen;

