#include "mylib.h"
#include "cex.h"

i32 mylib_add(i32 a, i32 b){
    return a + b;
}

i32 mylib_mul(i32 a, i32 b){
    return a * b;
}

CEX_NAMESPACE_DEF struct __cex_namespace__mylib mylib = {
    // Autogenerated by CEX
    // clang-format off

    .add = mylib_add,
    .mul = mylib_mul,

    // clang-format on
};
