#pragma once
#include "cex.h"

i32 mylib_add(i32 a, i32 b);
i32 mylib_mul(i32 a, i32 b);

struct __cex_namespace__mylib {
    // Autogenerated by CEX
    // clang-format off

    i32             (*add)(i32 a, i32 b);
    i32             (*mul)(i32 a, i32 b);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__mylib mylib;

