name: UnitTests

on:
  push:
    branches: [ master, ci_test]
  pull_request:
    branches: [ master ]


jobs:
  linux-ubuntu2204:
    runs-on: ubuntu-22.04

    strategy:
      # Don't abort runners if a single one fails
      fail-fast: false

      matrix:
        compiler: ["gcc-10", "gcc-11", "gcc-12", "clang-13", "clang-14", "clang-15"]
        cex_preset: ["CEX_DEBUG", "CEX_RELEASE", "CEX_NDEBUG"]

    steps:
      - name: Checkout cex
        uses: actions/checkout@v4

      - uses: ./.github/actions/env_setup
        name: Setup env

      - name: cc setup
        run: |
          #sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          #sudo apt-get update
          sudo apt-get install ${{ matrix.compiler }}
          echo "Replacing: cc to ${{ matrix.compiler }}"
          sudo rm /usr/bin/cc
          sudo ln -s /usr/bin/${{ matrix.compiler }} /usr/bin/cc 
          echo "cc --version"
          cc --version

      - name: cex initial build
        run: |
          ulimit -c unlimited 
          ls -la
          echo "Priming cex tool"
          cc -g ./cex.c -o ./cex 
          ./cex -D${{ matrix.cex_preset }} config

      - uses: ./.github/actions/cex_test
        name: cex test suite

  linux-ubuntu2404:
    runs-on: ubuntu-latest

    strategy:
      # Don't abort runners if a single one fails
      fail-fast: false

      matrix:
        compiler: ["gcc-12", "gcc-13", "gcc-14", "clang-16", "clang-17", "clang-18"]
        cex_preset: ["CEX_DEBUG", "CEX_RELEASE", "CEX_NDEBUG"]
        include:
          - cex_preset: CEX_C23
            compiler: "clang-18"

    steps:
      - name: Checkout cex
        uses: actions/checkout@v4

      - uses: ./.github/actions/env_setup
        name: Setup env

      - name: cc setup
        run: |
          #sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          #sudo apt-get update
          sudo apt-get install ${{ matrix.compiler }}
          echo "Replacing: cc to ${{ matrix.compiler }}"
          sudo rm /usr/bin/cc
          sudo ln -s /usr/bin/${{ matrix.compiler }} /usr/bin/cc 
          echo "cc --version"
          cc --version

      - name: cex initial build
        run: |
          ulimit -c unlimited 
          ls -la
          echo "Priming cex tool"
          cc -g ./cex.c -o ./cex 
          ./cex -D${{ matrix.cex_preset }} config

      - uses: ./.github/actions/cex_test
        name: cex test suite

  linux-valgrind:
    runs-on: ubuntu-latest

    strategy:
      # Don't abort runners if a single one fails
      fail-fast: false

      matrix:
        include:
          - cex_preset: CEX_VALGRIND
            compiler: "gcc-14"
          - cex_preset: CEX_VALGRIND
            compiler: "clang-18"

    steps:
      - name: Checkout cex
        uses: actions/checkout@v4

      - uses: ./.github/actions/env_setup
        name: Setup env

      - name: cc setup
        run: |
          #sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          #sudo apt-get update
          sudo apt-get install ${{ matrix.compiler }}
          sudo apt-get install valgrind
          echo "Replacing: cc to ${{ matrix.compiler }}"
          sudo rm /usr/bin/cc
          sudo ln -s /usr/bin/${{ matrix.compiler }} /usr/bin/cc 
          echo "cc --version"
          cc --version

      - name: cex initial build
        run: |
          ulimit -c unlimited 
          ls -la
          echo "Priming cex tool"
          cc -g ./cex.c -o ./cex 
          ./cex -D${{ matrix.cex_preset }} config

      - name: cex valgrind
        run: |
          ulimit -c unlimited 
          ./cex -DCEX_VALGRIND config
          ./cex test debug all

  tests-windows:
    name: ${{ matrix.runs-on }}-${{ matrix.msys }}-${{ matrix.cex_preset }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        cex_preset: 
          - CEX_DEBUG
          - CEX_RELEASE
          - CEX_NDEBUG
        msys:
          - mingw64
          - ucrt64
          - clang64
        runs-on:
          - 'windows-2022'
          - 'windows-2025'

    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: 'Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.msys}}
          update: true
          install: >-
            git
          pacboy: >-
            toolchain:p

      - name: 'Test cc version / config'
        run: |
          git config --global core.autocrlf input
          cc --version

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: cex initial build
        run: |
          ulimit -c unlimited 
          ls -la
          echo "Priming cex tool"
          cc -g ./cex.c -o ./cex.exe 
          ./cex.exe -D${{ matrix.cex_preset }} config

      - uses: ./.github/actions/cex_test
        name: cex test suite
        with:
          shell: 'msys2 {0}'

  tests-macos:
    name: ${{ matrix.runs-on }}-${{ matrix.cex_preset }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        cex_preset: 
          - CEX_DEBUG
          - CEX_RELEASE
          - CEX_NDEBUG
        runs-on:
          - macos-latest
          - macos-15-intel
    steps:
      - name: Checkout cex
        uses: actions/checkout@v4

      - name: cc version / setup
        run: |
          echo "cc --version"
          cc --version

      - name: cex initial build
        run: |
          ulimit -c unlimited 
          ls -la
          echo "Priming cex tool"
          cc -g ./cex.c -o ./cex 
          ./cex -D${{ matrix.cex_preset }} config

      - uses: ./.github/actions/cex_test
        name: cex test suite

  tests-linux-alpine:
    name: alpine-${{ matrix.arch }}-${{ matrix.cex_preset }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cex_preset: 
          - CEX_DEBUG
          - CEX_RELEASE
          - CEX_NDEBUG
        arch:
          - x86_64
    steps:
      - uses: actions/checkout@v2

      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Run script inside Alpine chroot as root
        shell: alpine.sh --root {0}
        run: |
          cat /etc/alpine-release
          apk add clang
          apk add musl-dev
          apk add git
          apk add file
          apk add pkgconf
          apk add zlib-dev
          apk add compiler-rt
          echo "Replacing: cc to clang"
          rm /usr/bin/cc
          ln -s /usr/bin/clang /usr/bin/cc 

      - name: Environment
        shell: alpine.sh {0}
        run: |
          cc --version

      - name: cex initial build
        shell: alpine.sh {0}
        run: |
          ls -la  # as you would expect, you're in your workspace directory
          echo "Priming cex tool"
          cc -g ./cex.c -o ./cex 
          echo "Compiled cex executable"
          file ./cex
          echo "CEX config"
          ./cex -D${{ matrix.cex_preset }} config

      - uses: ./.github/actions/cex_test
        name: cex test suite
        with:
          shell: 'alpine.sh {0}'

  deploy-release:
    runs-on: ubuntu-latest
    needs: [tests-macos, tests-windows, linux-ubuntu2404]
    permissions:
      contents: write  # This allows creating releases and uploading assets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          echo "BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

          cc -g ./cex.c -o ./cex 
          echo "Compiled cex executable"

          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.7.34/quarto-1.7.34-linux-amd64.deb -O quarto.deb
          sudo dpkg -i quarto.deb
          sudo apt install zip

          quarto
          zip

      - name: cex initial build
        run: |
          ./cex build-docs
          cp docs/docs.html docs.html
          zip cex.zip cex.h docs.html README.md

      - name: prepare web site
        run: |
          mkdir ./public
          cp cex.zip ./public/
          cp cex.h ./public/
          cp docs.html ./public/
          cp ./docs/index.html ./public/
          cp ./docs/install.sh ./public/
          echo "cex-c.org" > ./public/CNAME

      - name: Release latest
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          body: |
            Latest automated build from main branch
            - Commit: ${{ env.SHORT_SHA }}
            - Build date: ${{ env.BUILD_DATE }}
            - Triggered by: ${{ github.actor }}
          files: |
            cex.h
            docs.html
            cex.zip
          draft: false
          prerelease: true
          generate_release_notes: false
          overwrite_files: true

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            cex.h
            docs.html
            cex.zip
          draft: true
          generate_release_notes: false
          overwrite_files: true

      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy web site 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Personal Access Token (PAT) with write permissions
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          # The folder where your built static files are located
          publish_dir: ./public
          # Forcefully orphan the gh-pages branch to avoid history conflicts
          force_orphan: true


  wasm-enscripten:
    runs-on: ubuntu-latest

    strategy:
      # Don't abort runners if a single one fails
      fail-fast: false

      matrix:
        cex_preset: ["CEX_WASM_DEBUG", "CEX_WASM_RELEASE"]

    steps:
      - name: Checkout cex
        uses: actions/checkout@v4

      - uses: ./.github/actions/env_setup
        name: Setup env

      - name: cc setup
        run: |
          echo "cc --version"
          cc --version
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install 4.0.16
          ./emsdk activate 4.0.16

      - name: cex initial build
        run: |
          source ./emsdk/emsdk_env.sh
          echo "EMCC / Node.js version"
          emcc --version
          node --version
          ulimit -c unlimited 
          ls -la
          echo "Priming cex tool"
          cc -g ./cex.c -o ./cex 
          ./cex -D${{ matrix.cex_preset }} config

      - name: cex wasm test suite
        run: |
          source ./emsdk/emsdk_env.sh
          ./cex test debug all

  clang-tidy:
    runs-on: ubuntu-latest

    strategy:
      # Don't abort runners if a single one fails
      fail-fast: false

      matrix:
        compiler: ["clang"]

    steps:
      - name: Checkout cex
        uses: actions/checkout@v4

      - uses: ./.github/actions/env_setup
        name: Setup env

      - name: cc setup
        run: |
          sudo apt-get install ${{ matrix.compiler }}
          sudo apt-get install clang-tidy
          echo "Replacing: cc to ${{ matrix.compiler }}"
          sudo rm /usr/bin/cc
          sudo ln -s /usr/bin/${{ matrix.compiler }} /usr/bin/cc 
          echo "cc --version"
          cc --version
          echo "clang-tidy --version"
          clang-tidy --version

      - name: cex initial build
        run: |
          ls -la  # as you would expect, you're in your workspace directory
          echo "Priming cex tool"
          cc -g ./cex.c -o ./cex 
          echo "Compiled cex executable"
          file ./cex
          echo "CEX config"
          ./cex config

      - name: clang-tidy checks
        run: |
          clang-tidy $(find ./src -name "*.c" -o -name "*.h")

      - name: clang-tidy std checks
        run: |
          clang-tidy $(find ./cexstd -name "*.c" -o -name "*.h")

      - name: clang-tidy std serdegen
        run: |
          clang-tidy tests/cexstd/json/advanced/serdegen.c
          clang-tidy tests/cexstd/json/basic/serdegen.c
